apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-headscale-config
  namespace: headscale
data:
  config.yaml: |
    tunnel: 938c896a-6c08-45cc-b327-e860a9724ae4
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: headscale.shublab.com
        service: http://headscale:8080
        originRequest:
          noTLSVerify: false
      - service: http_status:404
