apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - configmap-config.yaml
  - configmap-acl.yaml
  - service-headscale.yaml
  - service-derp.yaml
  - deployment.yaml
  - ingress.yaml
  - secret-cloudflared.sops.yaml
  - cloudflared-configmap.yaml
  - cloudflared-deployment.yaml
