apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-data
  namespace: headscale
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job.longhorn.io/snapshot-daily: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
