apiVersion: ENC[AES256_GCM,data:B7w=,iv:JbUaboUXU0lffFp8vxbMhT3DxifGuDUDeqAQTaSs1Yo=,tag:Gshqcl4AJ+QGFpG+wLGxaQ==,type:str]
kind: ENC[AES256_GCM,data:nmPMMe87,iv:Q1zLH89blKF8pn7O9AzsvLfi2lk+oNgAM51GCZaI/S4=,tag:gX9x9OKWVh8yJqobzu3RFw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5I6LzTaFZzp0DYzL7SszMltVdep093E=,iv:s+TLVGUIcsd92z5TUHFtlQanGTIFKHVQaCaeyJUuw4U=,tag:+0u3LdogFwFhUe+h0dyjwA==,type:str]
    namespace: ENC[AES256_GCM,data:cpLULBS1/DSi,iv:HvFQzmJkK1q3K8EAPbozpkTx+68QDio7t/lXNHqiy2A=,tag:CndLIL3MjNaHzDlPOEyWtg==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:jgsoH5XSOuNCekC/tZ9KB7ezK+iroL54ERt9zAyYtmvax6/6rz1Sq3MlZohdaUTdq8s9BANdyPqy9mVXEA+CsHJsGmCGLD/ZLhAJULVW9kWcPVlekATOJjBwhzmk+8uQ9ZD31C0MbP/XOLHEnfpnJwsRQdYg0XWLaiXoEyFt/sWvAiADmZmbvaiLndDdR7uU7hNb5JExMk+e/TXEifTxxdGWShY5bE100cZ0vdZwHw==,iv:v+hrmtm9WGAwsxZYDiTMY5mnCNTzNNzXoRputBcdGfY=,tag:r3fVR8bm7auHB7Bb9rOWIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZWE5K1hENjdTcE1Ec3Vj
            M0RsUmRQb2hTYXB2d3VkVnlYNU53RllVcVJnCmxGMVlZUUhabjJNMnFYZmFuYXhF
            YXZOVFJhN1FRMVJiSnFldTlNckFWWWsKLS0tIHAvM1R4dDNXRXFIV2xPQjdzczJO
            cUVFYmJRd3pLOExlN3FxOHo5Z3plMXcKlFWoGjoR83PuEY+p+IUY8XtYzivDJScl
            yY3TMnsp3CrUgR5lr9PpMfaCVMC4GhxJSEOECVYsBBpKZJiaZmxlkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T17:52:51Z"
    mac: ENC[AES256_GCM,data:4VfMNeymieSMTgEgmo2L6rOVFMa2MrCxD4nCEJM3dj8h6PjY7nyGe0FCCOpSZyoLS5QqXoMA1o+kbnslBFexnnq+Z33fqZUcUvmZWU7PqwmMMJUEPtZBQk5am5pjUiLjanPvwxQDaWsASa/QXtfM6PeLF5NmhjHy6CwamBVBPlE=,iv:dHIA4594XRMvMB5jO45ndKT6nqqmzu+dPzjkoXfm3wE=,tag:amZixEEIDePKlCpK+vVntw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
