apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: main-l2-policy
  namespace: kube-system
spec:
  # Matches common Linux NIC names (HP EliteDesk uses enp* or eno*)
  interfaces:
    - enp.*
    - eno.*
    - eth.*
    - ens.*
  loadBalancerIPs: true
  externalIPs: true
