apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: better-booking-bot-data
  namespace: better-booking-bot
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
