apiVersion: ENC[AES256_GCM,data:YrA=,iv:fxG1hSUMqs7jBBdXogRrTie5f9S7i/5ddi4a1hrcHWk=,tag:+3FxsKtcJIfUdA3GV3YrbQ==,type:str]
kind: ENC[AES256_GCM,data:W4md9NXH,iv:ZrSxvmuDJILxMGfSLh24leAw/sLsAh3hugJKqNzyb3A=,tag:QhX72rvM4SVFGoP1Mwhx8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QDFn6ID51ttsUymuRQ5huTza/IAX4udjDwMdrNY=,iv:eDTKrpPVREbVDVqVwJ06GDf3jzxYPm23ha64t7nhzI4=,tag:IkbKa4C4QbnCv7FzfFPHkQ==,type:str]
    namespace: ENC[AES256_GCM,data:DAgNy19yz5y4FFkWazKfs58r,iv:xIaIZIK3MRQSll0mbaRXJDRtFDqubkkuRNbFrYCgVd8=,tag:/GtQcvjxQ6H3Wg9EnvoP4w==,type:str]
data:
    users: ENC[AES256_GCM,data:AQm0obKVG6AsEgr2fnZ4Vkwqk/67dWzQKDNtU4ZLjef31iU6l9oGXWe/Y/bs2CP9ltGSpj2XKqTgQgyK,iv:9rO2uxvYLYIFtzOrk7oRWIrHEk1GO9inLPlR8gPBs9Q=,tag:EKHDF11F+vkvjsoTJ7c0rw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVjVCeWFrM2dpUFZuYlF0
            MnFvWFlWcWJVVElDS3FTeHQ5a1pZaGR1OW5BCkFod1ZqVHJBa1J3RGQzTU15VGJB
            MkZNa2UxL1BDRlZaZmhXcjhCQXR6dVEKLS0tIG14UGt3ZXNyRC9ZM1Y4akxwNjBv
            UGhSSGxQOFJoaXRlYkZINVRjZkM3QWMKebBDcN+Q9l/JvHptO9gyhD6iavy29F3/
            pWasNiWJmY3HjHYyFPO41944V0qvtz1V4OaiC7KKZ0oNmd1jmp1jsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-18T11:05:06Z"
    mac: ENC[AES256_GCM,data:njUv891GJXSHYNF+riFPVZh7Gjb2222krR8Go8dWTSBzpeznvlALLuitdOF4carshDMFgiP1kSIwMhkTQoWPtiyfs0a9xtQcqrJ0gRgKRkRnPlhYh+esp0I+0O9ndIbWGR/6cB4qde19dbkHV44b1FZxA/1ul+8YSIGPBSlnY5M=,iv:zQNFYbO9MB23cOh8AV7n9TGrNpKnG+SpAsdBjSzVx9c=,tag:tmkMrAbgzJKXWGJXWKBf2g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
