apiVersion: ENC[AES256_GCM,data:HhQ=,iv:CF+cXSAVsA5MwLyl9N74OMG66KPmfpMr8ewoBFYVXcA=,tag:NrZklH01693lxuq7+eeZGw==,type:str]
kind: ENC[AES256_GCM,data:F/l1GVl0,iv:PwDPqrQRLciYw+X0NdyAa7WB0PFdCQ0bBtYtVLNxIpo=,tag:ETQc2QphF98PoFSxD5PKvA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:saEyssOEX/DgueN2+ZBTeMA1lnb/ZQuw,iv:KI5PhXBoa5+IoD/fBMLO7Wq+rNdXitlklE4MPnsUtJk=,tag:wr6Ql0VKoXRTzEtsPb44ZA==,type:str]
    namespace: ENC[AES256_GCM,data:in+ibGeVnp7ve0pybvWJITHd,iv:fPXJvvJJ59GDtW+2xjke7EvWgLgA7H+0RntuEyknSOI=,tag:7ihx6yOX55DDs79U+ICkYQ==,type:str]
stringData:
    BETTER_USERNAME: ENC[AES256_GCM,data:NWG7MDuRlVIF8+GdR477IvpRh2F/WSE=,iv:dSoAVRWpCc937o7dZQHL7lae9j6th4hAAOVaGXD4+OM=,tag:7HaNPhd2tF89eT8VD43PpA==,type:str]
    BETTER_PASSWORD: ENC[AES256_GCM,data:2uXk8LTWC8KCax8AehyXbNbqU+Y=,iv:Rc8zB6+T/BNmTyYDW9smKKr8ckPxOBzkBZflH2/CPzQ=,tag:Ln7GyhS0wxMr/bCGY9ZiRw==,type:str]
    CARD_CVV: ENC[AES256_GCM,data:xQGw,iv:nrT2/jbPwLN54ssa8/d2EwBt1PNbxxqJ837n3juJoxk=,tag:XErdoQKfAU+QyRlEmrzpOw==,type:str]
    NTFY_URL: ENC[AES256_GCM,data:wtYsnwjDABMNpUVGzIHXQm65/XXLDsi2,iv:rO2GtyuKRgakkLDtw0greI5ZxdJ2xfIxelKb0Zilh0k=,tag:/q1grSuGAF/Sf9ccliRWBA==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:sOdiABhmxGCLhB0/ntU=,iv:dyHjAuiMFkDCkkgYnOMt3M/vDE5DzkSKCq1f0WZdv8I=,tag:Wnpaz0Y7c1wBqp/vRGbWjg==,type:str]
    NTFY_TOKEN: ENC[AES256_GCM,data:QQAoYzcpldOza52+YVTwvlLQlJ0zwoEycLWvs6VX+uk=,iv:jrvyGPhZvklxFOnp0FSpuIaKhgw0qd9AtBM5uM6C6FI=,tag:M/p/UQlwgHMyRvmEPBHc8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cG9RbnNtL0hSTHJDeUJJ
            MjAxREdXbUJSdVEyRElDbkorNW42TTlmUHhJClZuMHM1ZXdLaDh6eEJJRm4vc1Ir
            Ui82Q2JUK3dJQkFOc1pzR1M0Z3pvUFUKLS0tIHV2Wmppbm1FTGxHZUZ2SVNBMVBn
            eENNYlB3NlJKVVRUb1VUVVFEdkxtUDAKdGhOtLjnkJGs+j2y6BLh6zFXFdLG9IPK
            HQCwS/PvmmzGO6PXLfpkYvVBkVLeK4LgE2IuEjixUk8Q//+od70qCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-18T10:19:41Z"
    mac: ENC[AES256_GCM,data:foCHokCwYfLHxkhMSPPAZUzgenfr4k/90LQ724CVtBXdh/M9P+OLZKsrcN4AaaD3Z0FtXM/s2/VtI3CNs9aqPi2IIKE6EkAIvYuCkgvXRzDTNYa/K1tG8s/Khr+AEnFt60dk4vRWKO0GTITFb5pF/pNHloJTjnRBuiyY4RpfWJU=,iv:DnOsXTxNPAocGtn8zP/ZWo7U5wIyzj/6Ju0fHgEX594=,tag:+uYkMbooKAaMMutYlEGp9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
