apiVersion: ENC[AES256_GCM,data:AII=,iv:gVV32IvUBIQHum3jDNcOljfBCbvvcRJC2/LB1EQuswg=,tag:I0q8+g471ziv8GgGifgkXA==,type:str]
kind: ENC[AES256_GCM,data:8/6w2PBy,iv:JHkHdzpye2Cc+9d/++qYv/H5PC8MMMiU11v3ldIkahI=,tag:W4O192sQ/jjSSrEMF1zulA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:snacqoWFTUEK0JGHZDeWnzJqApeWCxdJ54bjm+Q=,iv:cT3ctZelQtkNaPB9jV/NlOvNmXr+z2h17D/UQ5fe3jc=,tag:SISI1llDRDPOndl9zQrtJw==,type:str]
    namespace: ENC[AES256_GCM,data:o1clX1+SpsPplEylfFJxHmjI,iv:T8pU5ckS8+Pb7m2ZZG+/dxKfNQtKIgbB+WFFtihpUz4=,tag:jejByge3Ke6ESAozYaWEVg==,type:str]
data:
    users: ENC[AES256_GCM,data:EIiWNHZJ6X43eUQxadsFZCESeOUBgT5sRiW8pxtC5b4pZ1q1AhQG3FsA55vxTAbed+e6K0vTOt7F0i//,iv:PVCBpiv+7vY9rjqXGw2xOPd7DY+heCZ7l6wapiQiW0A=,tag:u2rdUvO2I53lMd2Up7REvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cTk0YXRZTDdEY2t4a0JM
            RkRBSlJOdzMyNXNuRmdlSXNMa3hyNEVIeVRBClFwZVlpS05VcU1HcUFrcE1SWnVy
            TjlYVHFoUFFqeXlzeVQ2bEMxT0RDancKLS0tIFN4V2NXUGp0QjZWUVEwYXBXNFlJ
            Z1M5ZktSdjJ4WXkydjJhbVZYaTdSaHMKnG/b6WgLjiYaLq4fY0fECRnXEvtEDHfV
            UK9QQEWs8075XXPqOzhRqpW9eDc9lGcaMyqefp/tLqQ/+5u3hg8C1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-10T16:36:27Z"
    mac: ENC[AES256_GCM,data:hhckiRnLjoUoRZOjuVtUTnDeqFh0AYceuwag2GDQXCym1nwZPkkLeB2NkPrGmXX75W9DT+0cwikzR1D6j4T+LmPs5TZikHZ8n3ooCBusMcpE7r0F8G6GoHdkKpcQPMfy80ZthDN8q9hJLypAHoogYzAqkisrgqK0r2bhoq5F8t0=,iv:JjUQN29XEwN1Uu4wg+n5t7nAYDnopOfmKx2wLg4GWIg=,tag:9urhgWyZghCaCTV9GX+OCA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
