apiVersion: ENC[AES256_GCM,data:8+c=,iv:zChbIf2xUM7hOrKsWuW33ZsEePhCQyw8TSdwrJFiUSA=,tag:TwaI2oy+gQXzRV/992joQg==,type:str]
kind: ENC[AES256_GCM,data:RJv+JJIg,iv:Mxk9o1JXS2epPysg6XIDItClTQPZzwOB+Si1H3V0nYM=,tag:gDZsk7rTmW5xsr2r/CpJdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7Y6Ll+4xY3odI+oxuIhuV8miewoznlozRQQAMuI=,iv:pR6EIbJ2EOny07eDSogxEmZiuuiQyzRlbWXwQ46e6Js=,tag:5S9tnX6Bul44fe7D/PhwhA==,type:str]
    namespace: ENC[AES256_GCM,data:WA1NRJ1s2swv/oD0l2Czx1gB,iv:MkRHHwKOQijVR/yFyzK3nWmPtlSrzMooIGV2XFfS6h0=,tag:t37MBajsg7RzFScarOhxeQ==,type:str]
data:
    users: ENC[AES256_GCM,data:TdSPNZdE/pgB9LbY61mSRmOiDi8Psiysvh4oknDwQLsx8ME/lMjszGtO0sBT9nuwl4aVrks9Y6Dr5D1P,iv:i6gAeVG6qHedc3Nh9PaiKcyFoxDt+Il7Q8ua50/7huM=,tag:mpffh5+zXkaL5hU2Q3hLWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWXFGRC9DbnlJZjRrOWNR
            TXNPN3ZSbkkxWmJDQnNTK05Ed1h6NEpYQkU4CmsrSnhOVmZTNEo3MzJraklqVXRp
            Q0hVYU9sVFJPUDZGd1IwaDAwRTZoenMKLS0tIEEyWWVFa1F1bDRvN3NHcVdvY0Vq
            R3BIS29Ia3YzRVZLMG9QdSsrSCtGWkUK0VIYdzSlIBRDGk74pebM9humQm5jxakc
            iHxdNGCUcLC2yzVj00bAqZsZA1HR1mXNTP2GBw8MthtTPs+RpmY5Bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:40:01Z"
    mac: ENC[AES256_GCM,data:aJK25LUGRFUKNosNxbJLxvQFWN8mM8aKsp9/8wFdE7/a4l6tzdiTwuT51hqxKPyeO6ajFzsuaIC7yiJGrbZ3VXScLEe0kEUj9BYOyEegEbzOrXvIAOrr6wQWVa5F/c37bpGUVymWDgK9UtWu1SgCjBXaSPmsG1ySTCX0lw7LNUA=,iv:LMl3VUcjSs07i++JYwWYcPjqlu2HtrsxiGEC7B0YLHw=,tag:afZWh4hIOLlNXZejM2Q4/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
