apiVersion: ENC[AES256_GCM,data:BD4=,iv:lTn2xANtwJH2Q51oQXxfdo4P+sK2o8ycRMg0kPA2kG4=,tag:RCVx1WKu2RZmPGImaqIIkw==,type:str]
kind: ENC[AES256_GCM,data:rXsBJi2K,iv:YSA2Mw8T3kU9Phy8jHTwr63UPg0/oFBWLv9ITDbzx98=,tag:fqsfuoBwemUbsWvtd4XklA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6YtDTbXiIBPlkbbMoLZMXdJP+5Kni3qf,iv:UQoIJNF3v4bzZWs3Dcl5xXXVfnlDbFVgmDrzz2Pwmco=,tag:FSZfMWm1yr5rlOyCIv6FWg==,type:str]
    namespace: ENC[AES256_GCM,data:W3n6b5X0+Q9YZ53uEtnpfoeW,iv:KcHW3quKMJsBs8B8nyuhjf643YSH9atCOZ6HuZHGjag=,tag:paGhY/FIcFuNXp9GSfzKPw==,type:str]
stringData:
    BETTER_USERNAME: ENC[AES256_GCM,data:gEFI4PVoKHhuMe4kbLJielg9LPQ=,iv:QUn+DUCJiTKj69UmrpY9AY2GeDFadigDJnlUdwEA0mI=,tag:NofFAkwZCmBG8cfs032bqg==,type:str]
    BETTER_PASSWORD: ENC[AES256_GCM,data:TapbFiulZCA=,iv:z0LtMe+W9Cm1ltQrVqlnAARYNYfwIFWoR0inMtpAvaE=,tag:20iIFc5v0bPRL00iuWZ/uA==,type:str]
    CARD_CVV: ENC[AES256_GCM,data:+uD+,iv:5DSgvyu4kXEznVQXwRwOoqSF2R8zdZolx1U+PBj2Lls=,tag:BDNBLxq2xTqeiWyhqDi77Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV2hHRVA3bzhlZVA4L3BB
            REQweG53ai9rRmsrMUIzd09iV1N5L0FSZnhvCkNnMzFhbEllUlRNK2JhNFVhc05D
            WHN0US9jVGJKM3dKTTFrQW9PTis5bHMKLS0tIE5YQUtmZUVxUERQVHVGTlc5U0hI
            OWJhaC9DSmdxN2pVc3lqcmJKK3hiRGMKZ2TMssFzzoq484ICL8aU1q9N2YMfxzbx
            ue0GV8R1B0hzghhIgljSR781PkpfmWrWqQk1BiPqPnr/kY7kJBI3fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-10T12:29:45Z"
    mac: ENC[AES256_GCM,data:vxNe/zVUIkEM9yfwJLrcsfxHZc35wTShe9brJFgsV5mUIrIR+MmlLLThevowOBIx6t/c4Aax6pYNve7Y4N6ESSRJnT0PjEM+59+frGxzDkSW3OhghEoKDKTZ4hktcKHtKP8SCEdkSv8THStcnC4oW7SDFmvL4HrYP8cqVZdrOYY=,iv:yCisGrL8G7Qxb6HYymA0DHBETn9T3XQtUc6qluuVkIs=,tag:d3WnbKdkuemCxl2vswNZbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
