apiVersion: ENC[AES256_GCM,data:HhQ=,iv:CF+cXSAVsA5MwLyl9N74OMG66KPmfpMr8ewoBFYVXcA=,tag:NrZklH01693lxuq7+eeZGw==,type:str]
kind: ENC[AES256_GCM,data:F/l1GVl0,iv:PwDPqrQRLciYw+X0NdyAa7WB0PFdCQ0bBtYtVLNxIpo=,tag:ETQc2QphF98PoFSxD5PKvA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:saEyssOEX/DgueN2+ZBTeMA1lnb/ZQuw,iv:KI5PhXBoa5+IoD/fBMLO7Wq+rNdXitlklE4MPnsUtJk=,tag:wr6Ql0VKoXRTzEtsPb44ZA==,type:str]
    namespace: ENC[AES256_GCM,data:in+ibGeVnp7ve0pybvWJITHd,iv:fPXJvvJJ59GDtW+2xjke7EvWgLgA7H+0RntuEyknSOI=,tag:7ihx6yOX55DDs79U+ICkYQ==,type:str]
stringData:
    BETTER_USERNAME: ENC[AES256_GCM,data:NWG7MDuRlVIF8+GdR477IvpRh2F/WSE=,iv:dSoAVRWpCc937o7dZQHL7lae9j6th4hAAOVaGXD4+OM=,tag:7HaNPhd2tF89eT8VD43PpA==,type:str]
    BETTER_PASSWORD: ENC[AES256_GCM,data:2uXk8LTWC8KCax8AehyXbNbqU+Y=,iv:Rc8zB6+T/BNmTyYDW9smKKr8ckPxOBzkBZflH2/CPzQ=,tag:Ln7GyhS0wxMr/bCGY9ZiRw==,type:str]
    CARD_CVV: ENC[AES256_GCM,data:xQGw,iv:nrT2/jbPwLN54ssa8/d2EwBt1PNbxxqJ837n3juJoxk=,tag:XErdoQKfAU+QyRlEmrzpOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cG9RbnNtL0hSTHJDeUJJ
            MjAxREdXbUJSdVEyRElDbkorNW42TTlmUHhJClZuMHM1ZXdLaDh6eEJJRm4vc1Ir
            Ui82Q2JUK3dJQkFOc1pzR1M0Z3pvUFUKLS0tIHV2Wmppbm1FTGxHZUZ2SVNBMVBn
            eENNYlB3NlJKVVRUb1VUVVFEdkxtUDAKdGhOtLjnkJGs+j2y6BLh6zFXFdLG9IPK
            HQCwS/PvmmzGO6PXLfpkYvVBkVLeK4LgE2IuEjixUk8Q//+od70qCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-10T16:36:00Z"
    mac: ENC[AES256_GCM,data:1Y8p+XEHvoelHLJtDzsAivbIEf+2118uDMy4t6VNkVI+Muc6VjJHJEclR9LaSiA9CTeUxNi2zhe/tk5/GJrqHYMWYvz80ZFVrUPJDiKFFn09lYecRMjmY5vksDBvFq+TTaUQgfVBbHz6bhfHIGLJv9N2mr17JujMt5t4wWG/AG4=,iv:R5b6qEAPbdVgNv1jgehD8wjDPirR2GbNuBcVNOnZ4I8=,tag:J/W4vTOiRmyyAgKjs0kCKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
