#ENC[AES256_GCM,data:a2KI5GDrFo77c8RetQOP8lcfxMh96Bw2JvIXSdqiQPjHfip8ZcrJdc1yDR9xC8iWP98sfgSZ/h+2Ols0eFB5KuDNucA+OPA=,iv:MKpOM6TyfqQIFKia+tlpdGi5BVviQkLNGF/e87nHDi4=,tag:5GcPjJVqm4LlYsw6dVOXZQ==,type:comment]
#ENC[AES256_GCM,data:1pYP7kuILUhXRs6z7GiRi/Hy5A+NwawfWCYxPgoTa161VbZ77mp4mTn/9ZPp3kJwlj30GvCWD116g2xTuPXs7bkZyGcvlKUm,iv:oYv+1wy97XZmaFn0hStQh90zJvn3Iov+B+nahlfvjlo=,tag:Zudnh19XNpnvQgq1AAcNYg==,type:comment]
#ENC[AES256_GCM,data:z4WXJLkI0o2xK8XgdYcM3a7MpjqD33QwGCUg/j5QUt5MjjE84ELInOQOKkQ7tA2/CTB8StB3PQW2K3TLqyTdTUYGDcqysg==,iv:0IBWoyBmXEbs7duUxXXaSDdNO7DFh15kPmyW5HOK+e8=,tag:Z6vwyB9qaMcEgXcKQKX0GA==,type:comment]
#ENC[AES256_GCM,data:zq2qjcL7BTR8mKjzFpSUpI2bQWohUk6VT2qMHrcCdIuomkdXifNZsB2rTP6MkrdSEvDcrCBCPP/OiOu0j36k+jjZkzPVhvg=,iv:A4OxmYi+cFW0s+dO6rsdUt+qKy7UKb8GngQf5Wd4JvU=,tag:c2zUXQAmBe6U5Ia2n+x9Mw==,type:comment]
#ENC[AES256_GCM,data:iOzvZ7jrSnCO6oXZ,iv:zWcUown7x/e1Dz4C8Gb20F9qGE1rv4GdoRnzkO2HmZc=,tag:Fkj6Y1echr0DMmVoEul7qA==,type:comment]
apiVersion: ENC[AES256_GCM,data:gYU=,iv:K87r4tW3hHVxJfLb9SB348s74dGe3xUvOS9PvCddQeY=,tag:0k1c1IekEPCSeOAu0uvzcQ==,type:str]
kind: ENC[AES256_GCM,data:nXblJxO+,iv:ECNcI5nKaRYUo3E69VzutPGdc/CSXU3ef+y/tNI2dBo=,tag:UIV28dYdlneyeTG12UTIXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2YIIqsg0O/L1UQiKg1G5QC/LjlCSA4EejP/O/ee5shkBNsSrMKNl,iv:IAebL77UTOTtUI0sIGng+Rpfxo+epIfxgXovxfaxAjc=,tag:lCcpbF/P2q5hMb4awfpLUw==,type:str]
    namespace: ENC[AES256_GCM,data:86VmWZwwID7kz6H6L9XIJpP2,iv:KZHVIKbTbJ0Vyt/qaQ7hpUVGxju1a2Psqh7bnttPZIc=,tag:IM+kH6L3JlyuFB7Q4fno2g==,type:str]
stringData:
    password: ENC[AES256_GCM,data:kGj7L4wwrGvQDb4IgmJZOyOA1RGMGf2y,iv:jTgTQx5JEMmdAq4/J3FVA/+s5qy6tijVHtWOdQA5kFw=,tag:o7lKk8taNDi+cMT8DgmKcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTXFKbnFkd3hURmpiY21C
            WkVpNURFZnlSb3EwdDNUT2NSam1Bd1hlS1dzCjdNYkFPUzZkSFZIVXllTUtkZVA4
            NE8xVFYxeEVqUFRPbkd2WXdVaEVBbVUKLS0tIEZvMEV3SjVtZnBUK0ZjTWdmWGU4
            UUxYaElCSGlRdzNtT3BCR21NNkt2ZE0K/1tOTVrxJ9X/1V3ZfoQEs7DdraAQvImQ
            oDxuyJ8xJagyl569arxlli8bzfGE83AEMBGCnSK/owjtdkiIRHVP9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:40:01Z"
    mac: ENC[AES256_GCM,data:irlwuqYsRSBC+eDSVGq/43wo5r/0wiXq8BKF6l4B3u3pvSdFqXCHNTMao6QXwGi+anXsPaj0Jr+MphIUa9M4jPSvwDJf9GgaSgLtquoFazqjYw3kW2taawPYyZ4ELvu3C103kuKMXkCdFCdhrdY98c4KrmjEVxhFgjB0qlZEMCI=,iv:jgxzL/mBBE/8I/muHfYEfpxRkvbYO9+SfqyGhneaPsw=,tag:wyDcw8KNPa4w/8W/X98VLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
