apiVersion: v1
kind: ConfigMap
metadata:
  name: recipes-nginx-config
  namespace: tandoor
data:
  nginx.conf: |-
    pid        /tmp/nginx.pid;
    events {
      worker_connections 1024;
    }
    http {
      include /etc/nginx/mime.types;
      proxy_temp_path /tmp/proxy_temp;
      client_body_temp_path /tmp/client_temp;
      server {
        listen 8080;
        server_name _;
        client_max_body_size 128M;
        location /media/ {
          alias /media/;
        }
        location /static/ {
          alias /static/;
        }
        location / {
          proxy_set_header Host $http_host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://localhost:8081;
        }
      }
    }
