apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-secret
  namespace: tandoor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: tandoor-secret
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/postgres/tandoor
        property: password
    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/tandoor/config
        property: secret_key
    - secretKey: SOCIALACCOUNT_PROVIDERS
      remoteRef:
        key: secret/tandoor/oidc
        property: socialaccount_providers
