apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: "24.*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: keycloak
      interval: 24h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: keycloak-secret
      valuesKey: admin-password
      targetPath: auth.adminPassword
  values:
    auth:
      adminUser: admin
    postgresql:
      enabled: false
    externalDatabase:
      host: postgres-rw.postgres.svc.cluster.local
      port: 5432
      database: keycloak
      existingSecret: keycloak-secret
      existingSecretPasswordKey: db-password
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: keycloak.home.didcot
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: homelab-ca-issuer
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
