apiVersion: ENC[AES256_GCM,data:pJA=,iv:70ewuiwlw8QdeTlsHJrRPh/hpSiSqSuRpn7N28BVWG4=,tag:GXkrsc7p22z+S8WfSUOJdg==,type:str]
kind: ENC[AES256_GCM,data:2U5oitNu,iv:XU3pepiuh5bauyxsCwtlMy3FsMh1SZEjJtxElPnykRY=,tag:MjMc2tXIHJtAQwYfwcjrfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3cSYIYyRBvpX+Qn/QNds,iv:KDXru+4IKtusX2Eq1A+NkH2dAB2WqqEpUf128wgo3YI=,tag:ModT+1MVbhirmO2i9VZJRw==,type:str]
    namespace: ENC[AES256_GCM,data:LCp+G5TTYQU=,iv:tCwoJ6pM1ryefnK/spdSnlo6HcCA4+pW/CtVYO5695c=,tag:3lzvae728xKkeTQXz6sENg==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:LmCkdfQrMjgdRpxXpjk77lk/svrzVWW/9hWoSWpCmek=,iv:U0Atv3oi/6l/W/ET8BoAbKYbi0Vb57cjuzfUR+3cZ40=,tag:RfNT7J4IgJIEPb9+JCVnjQ==,type:str]
    db-password: ENC[AES256_GCM,data:tgc7SnsV+vtOsIpTBLGg0WonoJDTL7ZN/X3ngsLD3cc=,iv:HhRyd95K3yvlq8ZsTeIlxjj7faKUsulAHJy3s3arH7U=,tag:j1vs5+ot465IFHWE63Qoog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVmE0WS9aNE4zZXlUZkZD
            UkV5dzlsUnJsUEljTDFHTWFpbWprM29qNkc4Ck5qTnRhL0EyWnBFZkRZWlUzZmF3
            UWJ1em5UZWx1a2J3QnN5VG1rRHZiejgKLS0tIDBuOGM1TUNrZmIyT0VoNXptNGU4
            RnMyZmhBZS84WFkxay9JWC9pamFwTnMKEj0FgV8tubowXhwGC79xe0NP/UwFnrE9
            wECk700rUXmC+93PDByjXQ6u45FBjJ5v65EZg+uK4noWqRKMaEXEZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l2j0cqvl7qv9ahx2levhr9r74sdn2ppf9fxsjhd9ey0wtrqcusaqjug4n2
    lastmodified: "2026-05-13T19:42:54Z"
    mac: ENC[AES256_GCM,data:IzCxtd9Kjq34JEpfwo5OxE3ExDlbVWi06jTctk+CvstiXkKtjNymCmHrd7SfAZPZrkUs7GpX6P8ltfYYnw58GEYYo3LxWMj/xNFxDZydOebcQbli+6hkYGNCqGGRTblr7YOvRdNhfOhB7i1T8ZW1xyi0KxJuDKU7/KydosmJ3q4=,iv:39FWrBV81ArYrf4ruUcxuF0FgDUQ9YZdEXaQd5Td/fw=,tag:u6OviFs47dEz9U4IwVo6vA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
