[tools]
yq        = "latest"
helm      = "latest"
kubectl   = "latest"
stern     = "latest"
age       = "latest"
sops      = "latest"
"pipx:ansible"         = "latest"
"aqua:alexellis/k3sup" = "latest"
