[tools]
just      = "latest"
gum       = "latest"
yq        = "latest"
gomplate  = "latest"
helm    = "latest"
kubectl = "latest"
"pipx:ansible"         = "latest"
"pipx:skypilot[kubernetes]" = "latest"
"aqua:alexellis/k3sup" = "latest"

[env]
_.path = ["{{env.HOME}}/.local/share/mise/installs/pipx-ansible/latest/ansible/bin"]
