apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: d09b7fdf-2c40-4049-8325-d97f1ef55a34
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: "*.shublab.com"
        service: http://traefik.traefik.svc.cluster.local:80
      - service: http_status:404
