apiVersion: ENC[AES256_GCM,data:ln4=,iv:XHfNlXc5U5d/VQz2ye4h+EPnumgoLhreCAA2AJsjazE=,tag:W43AH+90R0Ga5v68bzj7yw==,type:str]
kind: ENC[AES256_GCM,data:SxYm3ioY,iv:/keVetG/LAAxDBbYdIJVewjxASvFuTKE0IM8z4gtgkc=,tag:sOrYsEIGzPBFKHM9I1BKpw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:myNm7IbysQR+S1LYj9rgVVMf4lQzG7c=,iv:fDiQcU76AJIslwWro94JzH+5zQ1bquVlrAqwGtMXcOM=,tag:9optFuQkGzQ7iFvECZ22Mw==,type:str]
    namespace: ENC[AES256_GCM,data:x9F95caYXE3w0Fw=,iv:vmCQMV4kHiJvwQSuG0R51tZqwV3hps3zbj9cVEGJRl4=,tag:ZFdS6hynNDaImpYcaDSTvg==,type:str]
stringData:
    credentials.json: ENC[AES256_GCM,data:r7nMm2wVyWV6Oz/FH9e/VNH0r+CwZO0/K/T6SbXsyF1wuB0lbi6lNqSl1D8cYKYeLByfw6axm1ttLsqFCasWxWG3yclSWG4RV1BLGn8j+0RqMS4Z4+jIfn/t4mFNJcnXFkmpaYyYx4l+vb2PEUS0LeM9Tzpf71b11p08ymVW0L440KbjL5g0HlKME5AgenI0Hr+O7G528MsGlvFm3b99omY6N9lu8kwaJSRMNSV/8w==,iv:bXHP5bP+MhwOPJ2zFNKwEzpDdRVeDlQhv5aPSx8H6MU=,tag:9HqxFcLb0krRbu5H1P2EzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqR21hMjZpWTNlYVNVUzF1
            azhRQkJOR2t3UkxZaTkzTm42SW9tNHZieVZNCjJUV0ZHVWhOTGlGWXFUN1pEU082
            UFNueUFiaFVBQjVUMFVlL3pCUkFBRjgKLS0tIFlGc2Y3ZWh2dmpKQkxDL3c3bkxi
            R3JrNmtxM2d2UWNUT3NvdDZiZUFOd0EKIcHgxZEqyeHTsCKGOB2QpwqW2bMpndOz
            j7hTU0Ea5E6/wxf1Etl+fQxJRwLamlCdWWwLDeSfMmiznWBXKQ5d7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T17:02:40Z"
    mac: ENC[AES256_GCM,data:2Cg+FrFYZeXfcSA3OZtT00aZIJkmOTK0zJSQTG6U8AepBstJEvpUugEFw4Rd5yvSJ9V22JSWdGqKXBPA+g3LhUHicZkDb9Sf3UwdQP8cWnN79IUySB8eJ3HUvFqn3yg0UUPOSBZmgItkEQQ6aMN85Niho+coFm0c6kwsBZsZ2wQ=,iv:4HbGLYc59FxPVT1FHajbOCtpQWx792DwyFC/1tEto7I=,tag:tQbqwNkE2bxGKWmhLqltvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
