apiVersion: ENC[AES256_GCM,data:EQs=,iv:mNroM7QXEl02PXgyWhrYGwhNOJdCx8Bpj9WrCqlOAmI=,tag:a11xGU+hPgCdFIrV5DLccw==,type:str]
kind: ENC[AES256_GCM,data:2Z5PrFZi,iv:jPp4b/x8HK10FaNyl+gryIXqg21tRfejzsR+pPSp2VM=,tag:D0x6VAiqzaI95BdzCpqKxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iGdwIp0jsm1hBi5XijeKWao=,iv:gCJ8T1RGc/03v7iLXIzofmp/egZT31WUaAI0kInJdpM=,tag:x4C75Tomp6/i9zh4y/Ycug==,type:str]
    namespace: ENC[AES256_GCM,data:qtd5wSEmh5cqdQI=,iv:smb5/1WIeHOTPbxisp2JWhnStld2pUFd4LzL7xfiMrE=,tag:3RcU6oUl1JWWFTsgnmmw5A==,type:str]
stringData:
    token: ENC[AES256_GCM,data:1LsRv0tjRKNw/s5mo0iEKBzEWZcbfci2FiI+vw29dWNIVl/nSUF5MK4BtGXYQbVuf+oONGZMRUP7mpHYLEPXCxtK1Re+TwYH5MGf2pt2nMquMPbr8OCxCBanZ62VmIgcYjUMSVS+nBdvrSdXDTWEC0kT4Xn6LBwOYV6LNU/JIB0bWZ1SxGTcx0e0sKfEQSmHA//IcdpyvNquCENtLz9WGL/rG+Rm6p70k55DV2YnwMXN+ydZY/yoIg==,iv:W/6t0OMCJ8/gXoeJ9RMywmKp1Cb5l2gAm8icHsxLVwk=,tag:pafzmLSZmv+vya6i3azsTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSjhRVDc1OUo3cGtUQnNa
            NnN3c0VISXZtMkVDZGpIaGNLUG1vbGg0dXkwCndMOUd3M24zWjIwUFo2MVhpWEE0
            YjF0Y2FkbmlHeHB2b2dWenlWRDlBVGsKLS0tIHpucXlWd01peis5VUl2WjQ1N3Fv
            STdzSVpPT0YyMHA4UTJaWFdhdUxhcXcKRrbYIvqRSGVoeeBOPZjxW/D2f1hoNW7N
            IzQw+b6IOsqUzBdNEjp5YvF2o9h3nzAb8jJIYt4M1rj/zELkkeG3JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-19T09:18:47Z"
    mac: ENC[AES256_GCM,data:xBhdWWWdGQnEFPa9DofatdTEjoBtezx578Sy9JmNQQCcdBLM+z5QypkBaDB35L7Bw847XHO/V2qhEpajIFcHyiaf7QZJBbM0nos0tLLPLuJoUSW4SoV0PxYj6dQCc41UzqJmhoMgHyRS5igAH+xXd7/3rxme5HakP8mJHSiXaNk=,iv:3kHo+wN0t+fST/97F2QbgMrXX48avGgfZwxlSBLljNc=,tag:ThKDQrNa1pt8rH5BbiFyqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
