apiVersion: ENC[AES256_GCM,data:Pt4=,iv:bghr1JcFe0KbFRQDKmi3nXhYl8FK8F1mKZW0TG7KuyA=,tag:7/ML9waycQuj29/wFskoVA==,type:str]
kind: ENC[AES256_GCM,data:2dzi1As3,iv:SWRu5F8naUh8X9Btqqfh6gfWYrZfOY5EtbBy3uWFsHs=,tag:sAMgwe3KNVFXCnk+Sfc3BQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ON0vOx+N0JxqpglQs8X6GF8=,iv:Itt5wHTIrZ9aQ4nn/Mm3aJK/qPQQdj+B245aQmeTXWI=,tag:QkcYFuWhYIVFqtFH5/lwQw==,type:str]
    namespace: ENC[AES256_GCM,data:01qv6xpFSmfrSto=,iv:MUUFuLpoSZvHcfn4qmQhIpU1aZrq7OGU/xM7zeNntx4=,tag:Fw5lRqjb3424qGdasspOlg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:BULDhxfI1AUu2u1KOXGlUwjWSxTWUU7nUqjU2qjxZZ/6NBAaEGvgLvFWcVVAeH9W73GP5BjJL1Ve6NbmX/HLak5+P/LfHUlOq8UYlGLUlzc48osGXzW5cncMDKNiSS/Np65LFnR32tG8Sfuojkkb7GtJDcwYr7K0gtrpnRW57AjYVURRVbF3FCZg6S51M66XJJOqhuMYzQV4FIcB9pVNZS0LAOgv3QXvHItTznNl7gEiZl9LjR9Zmw==,iv:TjIMyP6KxJfgpHd9t6aI+3odXgWdUcK/h5tOFcZElXk=,tag:qXldbUbqnmQwOaJ35RMdAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMG5wWHdjT2hENHgyQ1Uz
            Y04vd2xyUGdtSnFTNTNiQ3BSZ25yNGM1cVZvCjZkYmxBVjA1cm5UZ0NPb3kvQXBv
            RE9HVUZPellueFlrV0wyVnUrb0JtQWMKLS0tIHMyYVFzQVBXMW1EbS84S2xOSVpR
            bUF2ZHJ6SGhtbVRiUnArdnB4RUNSRTQKApzIwDBc1IDzsAo8XQqaJgZq1QNxU1+f
            rlFC3Fntz2ETirQduKhcyR3oIwr6iwgrznln1DwwE8I6wCGQUlBrvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-19T09:46:36Z"
    mac: ENC[AES256_GCM,data:G/gT+PQeG52oLKZSTw2CR8ofuXdm8lNGz66F7HqihvAssQv9GaaWaM5dkQA+UhskAlp01ps/QKqLnQx8GaBpPChWFLkMXjqBzgLxsoPGtpb+ukOVju8OsEud+nCD8BuRzdjHzhYPhOQplgRbogiEiQX75aPhX3lHKuZlAbvSLXY=,iv:XTEf2aLNNnznlt+LR3bhd3Ua1apW8L8DCOCf5MD6q08=,tag:z6AuiUw5qNK8Cs69p8u8nQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
