apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pickleball-predictor
  namespace: pickleball-predictor
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: traefik-security-headers@kubernetescrd,pickleball-predictor-pickleball-predictor-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pickleball.shublab.com
      secretName: shublab-wildcard-tls
  rules:
    - host: pickleball.shublab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pickleball-predictor
                port:
                  number: 80
