apiVersion: ENC[AES256_GCM,data:FH0=,iv:uxaH1RjgX9IrOaB2ZsHDZBUwhgHaokUSskwwKwGUSYg=,tag:WhprdmQ2N3GvQIsP3bWoCQ==,type:str]
kind: ENC[AES256_GCM,data:RG65WZTf,iv:3swYhjBZW6KROQwW8V14HfaFxR/SV4eM+AvMIGsh9y0=,tag:lFuruDQCLFpmqnbijVXTDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I//rWdya1aOrV5D+tVvV8Lvg2rB4Q2EFxsw=,iv:SicLvselvMnR9AJaXABYVQFfohRXLAPGjNknOmvWhhY=,tag:rq7h19V2EAlndXAMKKJUDQ==,type:str]
    namespace: ENC[AES256_GCM,data:gesXDj08cEGW2nN3VlzdYLMrRJw=,iv:mCIKIu61P7moDfpyzh6r78PyeRswc2p66szbdz6aYUM=,tag:nzi/0UwKIS3CL8eOgW9I3g==,type:str]
stringData:
    SPOND_USERNAME: ENC[AES256_GCM,data:J1b3krPAgwtMH7t3AEkjU4dNaRntGhc=,iv:pxeIxzJGh67W06XYJuET5rtFhfte/RE0pmQXLB86ZL8=,tag:FK9HUjs5cly41jOoaipiGg==,type:str]
    SPOND_PASSWORD: ENC[AES256_GCM,data:qK8UopqUauf7EwQlVCEZbPa9oOg=,iv:6hXAymBCeJpJxopOXrp+VtTZEjhM7q4V7HW5ECcIIrk=,tag:itN1AM1u0W5hMKRtYXdeCg==,type:str]
    DUPR_USERNAME: ENC[AES256_GCM,data:okeVhZPPXRnxaTeWJoqHjXy0+RoTCoM=,iv:fUual/9gjP6Li3PxSphUVReTKjvYbjC+GrLlDugSyDU=,tag:zZaflmCvbQDoJSlljO6rrQ==,type:str]
    DUPR_PASSWORD: ENC[AES256_GCM,data:x7VZTMHcb/E1vJmWrN3e6QEpX7Y=,iv:fOBvgcbrefuubJpaAbdf/01x4X5j5/DzCuLKK8LTmDM=,tag:np1DlRmD8WYXPXT9CArpkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUW1HVG5oRzc3Q0duYVdP
            bDEwRGhkdTJITUNrZitxNHhFQVVjUm5EaXpVCnAwTTRQdkZOR0cwN2E4WGU0ZmhN
            RnFOK1ArSks0ajB6Y0U5WWtrMHA5Sm8KLS0tIDFZZktXeXhJaDJmYmhjeGl5QmFF
            bW1pcm9GM3FIWHJJZS9BbzVJZkVCTDQKVcN+Qp5Y0x66JvdLwSQjF8Fgj+/2d177
            rxY39uq3RwXUeP3iKNkY91xz3ykdngTWSxtD+etBZIAaeVzZmavrrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-09-22T10:34:33Z"
    mac: ENC[AES256_GCM,data:lT9+6wFx3be1akwJeMbkhlf/XOC00FFEfb3ptRIfPB+/2HA1SeZcjlyIb7a60PMfMOt4hgzeKCGbknYjcgBDnAb1xQJ+OStEGivgXMWvexDogZLkJPJ7uB+QCMhfHp2zCqs7CUu+bjdKoNOI1dsszDEbPUhbfdIMaGd3V4UHq7o=,iv:fOre5JfJlML0xPGIpn+tLHOY465UqMKvaZ6tV3x6W9Q=,tag:2XEE9pK5eY2NZKV2DzGGLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
