apiVersion: ENC[AES256_GCM,data:FH0=,iv:uxaH1RjgX9IrOaB2ZsHDZBUwhgHaokUSskwwKwGUSYg=,tag:WhprdmQ2N3GvQIsP3bWoCQ==,type:str]
kind: ENC[AES256_GCM,data:RG65WZTf,iv:3swYhjBZW6KROQwW8V14HfaFxR/SV4eM+AvMIGsh9y0=,tag:lFuruDQCLFpmqnbijVXTDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I//rWdya1aOrV5D+tVvV8Lvg2rB4Q2EFxsw=,iv:SicLvselvMnR9AJaXABYVQFfohRXLAPGjNknOmvWhhY=,tag:rq7h19V2EAlndXAMKKJUDQ==,type:str]
    namespace: ENC[AES256_GCM,data:gesXDj08cEGW2nN3VlzdYLMrRJw=,iv:mCIKIu61P7moDfpyzh6r78PyeRswc2p66szbdz6aYUM=,tag:nzi/0UwKIS3CL8eOgW9I3g==,type:str]
stringData:
    SPOND_USERNAME: ENC[AES256_GCM,data:GFCjhwiDgKEL5+a/G9o=,iv:2iZ3W+Rxdsi8iYqrH/AikkwsoQzLaL8l7To5BoyKLAQ=,tag:dzqD6WV7kfFQ/g56hBnHQg==,type:str]
    SPOND_PASSWORD: ENC[AES256_GCM,data:qhru/uVFTA20EQ==,iv:9ZYwDOkioGpUCz/BUgusSCzK+JIiz2o17NF6X4V2BSs=,tag:IajeMyTEeATdAjwtQxxrGQ==,type:str]
    DUPR_USERNAME: ENC[AES256_GCM,data:EDlCoabnCD1IDTxJBg0=,iv:8FeQPTlwUhwzQBuj3e/62qxzSq58XM7m8Ih83GQyX9Y=,tag:VooIOIwurOUnFoNh4Fnisg==,type:str]
    DUPR_PASSWORD: ENC[AES256_GCM,data:AU6eyryS8mwhQA==,iv:3ki9fQVxd2GYqnP7HIzpg/U+Wlix5+lW2QSfi5pTQK4=,tag:p8kCjQKuNe9HHJW3CmIWqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUW1HVG5oRzc3Q0duYVdP
            bDEwRGhkdTJITUNrZitxNHhFQVVjUm5EaXpVCnAwTTRQdkZOR0cwN2E4WGU0ZmhN
            RnFOK1ArSks0ajB6Y0U5WWtrMHA5Sm8KLS0tIDFZZktXeXhJaDJmYmhjeGl5QmFF
            bW1pcm9GM3FIWHJJZS9BbzVJZkVCTDQKVcN+Qp5Y0x66JvdLwSQjF8Fgj+/2d177
            rxY39uq3RwXUeP3iKNkY91xz3ykdngTWSxtD+etBZIAaeVzZmavrrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-09-22T10:19:11Z"
    mac: ENC[AES256_GCM,data:bl3ouYwvvvVJ/fKK6EfUOVTRncdEs7yOAg6kxCuxps4QRfJXyUPkNv+ddDlQOsguJXqV6abhIZaq4vCYUCsF4pbxM/GPU7etRIHDVuoUcVRqZc5DqhZuhWUXZlQhtIPoyn2Mh5IrdwCF3rx8QT8UqOoNWsQ04PFEPNzFeTiEWpQ=,iv:Zzg7j1xnkRZPUNWwMyQCbWXnt/sKeVCfoFW7v+gfg3s=,tag:I457MCBH7UeMNPEsTUM5xA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
