apiVersion: ENC[AES256_GCM,data:Up0=,iv:+ru42Mv/Vv5cyM5h4oJPBVrG+/YkGuUkRN1za/pByJU=,tag:FETPObDCNyfQTP3FY6Dj6w==,type:str]
kind: ENC[AES256_GCM,data:el7SXETt,iv:pqTtvXK7W9I1vChBQqEBsqHIhshyYgW8abL7nMjFf0M=,tag:IX9Vp8e+Wvz43LATTjcsSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CIkgKq9C2B5dXMVwxrbrUSRxTA8bOhbjeEX0bsbarw==,iv:V/qJnWOZhh3IitJ6LEuluirOb36usXuCfW/qeTXymck=,tag:4IKCfdcOWtwbPpKUTe5rcw==,type:str]
    namespace: ENC[AES256_GCM,data:vo0EkV/P3xMXMg9l8M090khYoUY=,iv:lfO0HrXitjCmx8KyJ9RZxt2oBQW5Wt+5SDHUSbA7Iw0=,tag:nyz4KHhs4hs9Eiej6DrlSQ==,type:str]
stringData:
    users: ENC[AES256_GCM,data:9eVZS8YizlXn8/3MNOvr2HW0LrNsrXvmEUxxDQFjFENK0np3ZCg93bzGHGJRVYS46JV+/dSV9bq+cVN00cN2WImVsacc,iv:EIe1lx0MTsHK9IooQ+bgZYeIlSQ9EQb0mpzuYao4/CI=,tag:GaqrzGNIqTq6qSKimNf/RA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQXNWanQ3YmpIbmpsZnZs
            dWJiQ2ZuMk00Ly95ZndYUEVLakFtbHFLMEVVCmxBU2FCNUJuZzF2ZjlUajRPQ0RO
            aGtqcEtTQ1U3dFFxNkZzR00wb1pwS00KLS0tIE9uWlJDQVB4REZTTE1XV2V2YVB6
            T3JraDNYOEhGREs2dERCcWg4cGlvOEkKtSIFLXt/8QSQ1EzDYYIvk0jaa8Sod+dX
            Bo/mqaN2IYpK2yf1vUI1Xmt/Y6HXTNHN2gmxsJKv8POSHN1FMTmLkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-09-22T10:35:37Z"
    mac: ENC[AES256_GCM,data:pu+Cp2cnU2dpKcmC3RZpxw5QXn+R1A4HiU2uplD/6DQCdbkNCapaxMWk/unng+EpzarBM/1x6Lw4CKofpF/EhBxSVh8B1fBf6oSlHtNiUprbHyr6QG0EVfW4sMhcXpM1b3+fBk9DVM2MnJn2ptayqDsxw/cP7Ai7tPZGwdSmETQ=,iv:XEhBaprKul/+Eb6dYNxq4LM72BAcC/nwK2gxFWGMRhM=,tag:raCvKYdn52Dg1MgQBCs5Og==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
