apiVersion: ENC[AES256_GCM,data:S+w=,iv:vxq3YVRXvjP9ns76W2/Pqso2PPXLcgYcN1Z+pcgYxzM=,tag:LZ9V3/Iw0EUMqcB5YVqo+g==,type:str]
kind: ENC[AES256_GCM,data:aSe8cvxo,iv:iOJCnzWXlPA/SB4MkX1bq6cf6MSYu2KdlCGnXQxdqs8=,tag:Ldn4B4v60l7XJ7k7zoMNQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FK2edhyyAdS5x/NrBkQe/nRc0Sf6e+zxIKqb7Xh1b06nGc6A5Q1hUms=,iv:BX8UVDCK0LVtjzqB6j1depwKcrwWQdQR41Xodf0NbMY=,tag:FA0joixmZ6+OsiOozZEk/g==,type:str]
    namespace: ENC[AES256_GCM,data:Y3DsxQsuRvQxTgsZ1D0J4ghG0t8=,iv:IWhF7eG4TXfhUPXdMaXQiDW3o2b+jClVcy58t+KvfNA=,tag:Cmqw7XlBtrwrDv5oapTm3w==,type:str]
stringData:
    password: ENC[AES256_GCM,data:RV44tw59i1QER8JI+EOt6txgoFQGIXVfZx7Pp1v3tvo=,iv:ZpCpRRRzZlEw4w8nNhq7phvCLInKYDn7LMfWdp2/1mM=,tag:S2t+T+scxaNRE35F83dT4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcUVoY09SNkpJa1BVN2g4
            NG1KcWh5T3hGL1lnS21vZzZjYXhrZWFDODN3CnhYTGdKSVo2WFR2eXl3US9rQTlp
            dlJvSk1IS0NTR0gwS21LZk4wWUx4OG8KLS0tIG5VTFI5dXdIUHhBbGdIS0NuMmxK
            eDMvY0dzUnV2a0FlVXdJamNjTDdUamsKTK1emj3WkuVsxjT+YkvfsM7vlOQ7DSCc
            F6TpPX+y3FvjyOm5V6tV0n3v0OOqcZO0oaajgvcD3q8HirTxRUE/Ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-09-22T10:35:37Z"
    mac: ENC[AES256_GCM,data:zO7OZyG/82flD2xtFP3yfPH6cmZzq3ApaOnmku0CUuyma6C0Xm2m7ipTSEUGc3uXc1AUwSwCuIHSTvhKXpk1VkYXE3pc2ekYLwmOVS60S1r63Kuk19nAyLw+API3kh0DsQtfONOdOzeGAd99BSacDcMKDeRLpIUVXac4B9RzOOk=,iv:AI07KUGw7Yj2eACDNEQp/mLIqX2l5OKxDWjOkmCMaLw=,tag:9uW4nyG8rWqbsuu7kgtykA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
