apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/networking/cert-manager-issuers.yaml
  - ../../base/networking/traefik-middleware-security.yaml
  - ../../base/networking/traefik/middleware-auth.yaml
  - ../../base/networking/traefik/secret-dashboard-auth.sops.yaml
  - ../../base/networking/traefik/ingress-dashboard.yaml
  - ../../base/storage/longhorn/recurring-jobs
  - ../../base/storage/longhorn/servicemonitor.yaml
  - ../../base/security/crowdsec/servicemonitor.yaml
  - postgres
