apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/networking/cert-manager-issuers.yaml
  - ../../base/networking/middleware-redirect.yaml
  - ../../base/networking/traefik-middleware-security.yaml
  - ../../base/networking/traefik/middleware-auth.yaml
  - ../../base/networking/traefik/secret-dashboard-auth.sops.yaml
  - ../../base/networking/traefik/secret-dashboard-auth-plaintext.sops.yaml
  - ../../base/networking/traefik/ingress-dashboard.yaml
  - ../../base/storage/longhorn/recurring-jobs
  - ../../base/storage/longhorn/servicemonitor.yaml
  - ../../base/storage/longhorn/secret-basic-auth.sops.yaml
  - ../../base/storage/longhorn/secret-basic-auth-plaintext.sops.yaml
  - ../../base/storage/longhorn/middleware-auth.yaml
  - ../../base/storage/longhorn/ingress.yaml
  - ../../base/security/crowdsec/servicemonitor.yaml
  - postgres
