apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secret/keycloak/admin
        property: password
