apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane-config
  namespace: headscale
data:
  config.yaml: |
    listen_addr: "0.0.0.0:3000"
    headscale_url: "http://headscale:8080"
    headscale_public_url: "https://headscale.shublab.com"
    api_key_file: "/secrets/api-key"
    cookie_secret_file: "/secrets/cookie-secret"
    cookie_max_age: 2592000
    cookie_secure: false
    disable_api_key_login: false
    disable_config_validation: true
