apiVersion: ENC[AES256_GCM,data:QNI=,iv:+TCYv2H9DuqJWQWItnxXgwRQ0PKBJ6/NKYPidjMk7rM=,tag:BrKXHOdcZPDoGwoLwsx+Ww==,type:str]
kind: ENC[AES256_GCM,data:AsCXlT2G,iv:3NkZgU7cB3NOSwOXC7k8DOjXR+jvaO7coROUKEjZWtM=,tag:YeiE8cXkT+0R7JIHrNYfOA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:E7bb7KRUv+DeBsyAFPDeEw==,iv:E+nSGhRseeIPZl0UFsOFUc1Wu7LVZcHz5s+LII5Dgr8=,tag:bTJW+yfJfgYReb5hO/ZP6A==,type:str]
    namespace: ENC[AES256_GCM,data:6Xg2QZLJ4O8R,iv:+97VzPkUModqCUAytkUI6GvTRCuGOUKsG8WbqRFt/1Y=,tag:BoFFppI5FW9QVY5V57WVTw==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:dn0HCr4nsIPbvAgY2rqAVI1OF2ppILNQ3MscOBx1twYQXNbTMuDy+esg5X5MpFLYmCXw0iS+EVZKMr9O4+gaGA/eneQgacdsaF802HmB0fZrec+KPzho,iv:QQxwhoE0JNz/K6QLjLt54FI/d7yFIVdQDc/9Hf+4hmY=,tag:4LUAkKOUB8kdCiZmhKT9uw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:iiVHo+D7pT/T5oSHM8Z/D+F9hfvX4lOteyuNCwsUNCI=,iv:mY1KPTbkS0wX9FEJbAXJya9VdIWET71R/QSa6xvRkQU=,tag:gdxFEfchU+emaOHNG77Bfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTHF5UDBUb3hxdGFTUlFh
            d0drWnp0YWlrdDhrT204V1Y0VXZVN2N5UXpJCmdndWpOazUxdWl1Q1JiL09jVWds
            NmpyNU9wMExaUmZZdE1ZSURIeE5pK2MKLS0tIG1UUmM5YjNOVFI3OG9VZmtkN0ZQ
            a0NHb09hSnhvZEY2K3lsK2xtY1F5dFUKRuek2OtKFE98kytmIXrfHEboNK2TW8WM
            zXz8Gw3xe4vQ1XoeS0ZrDUhshqYbbUSTcO0CHdEJhiqMa0ygBpiNHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-16T06:25:32Z"
    mac: ENC[AES256_GCM,data:3Q2CBPxjqBMjjW6F3ym22eI8Zd7BOCqAilqfRYTVAmTejWZFnEw2q8xFOqYcgjxbxsUxo1jDVixOga1abSAELBTFyGV7lWkkA2iMUwn9yFrFL9YVUrTTJvXfr4MbJ35e9rmZYVJPChPdUOZKL1BdP4eWhenocb1LexKQXn0R7Fs=,iv:2kuUQVieCPH3sLdn0N/1NY0i36RB4VU+7fPtvY0dwzk=,tag:+MIkQFUoQRXtPHtR8Z8FJw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
