apiVersion: ENC[AES256_GCM,data:xGs=,iv:2EgHdzyY04Iq9ZktW2ZP5GF0fu52kafIL16BS4S0QC4=,tag:wjhxBYTX7IU8zLOFFThXiQ==,type:str]
kind: ENC[AES256_GCM,data:KbaYbcHL,iv:Ml99l32TD9KIZBaNNhtgmZfiHVc059IhNzsHcw9C49c=,tag:PQhXk5uaGylcjTgv2R9Zmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2MwwsrHcsKDDyOMjHP2oGg==,iv:ZkNMXsj4yH6kDJxnx0X7YJHuX86U2NtPWmwLyO+hZVE=,tag:de3op/fKpTpiaNjB5HpCaw==,type:str]
    namespace: ENC[AES256_GCM,data:XQi1ZW0+NkPS,iv:UurJmTFBXcdQo1+s0hgq6bEkSDLBciq0cJ6ROlGvZm0=,tag:jloRMzRVugO9Z9GOm/FHtg==,type:str]
stringData:
    api-key: ""
    cookie-secret: ENC[AES256_GCM,data:Qn/qc1fSXlGv3qSxmTj1gNLFwwlHWYcssQENRf4wODw=,iv:VJEc29lKVP5g3a4jDlB1YJTE4WC7gS/bGAwkUN320cA=,tag:+pi8Bw9zhJKDlmw2AQ4IJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSnNmRTRBZ0NGTDQzcnZW
            NzRCMVd2Q1gwSHo1dHVETEludnZDei83VjNrCmpTR21RK1AwQjBUQXZYM1BiZDdQ
            NThVQmZsbWlNQUdUNkttWnV4cDhkUzAKLS0tIElhdlFiWld6YTBhS25ySTlhS1hn
            cWR2ZGNUQ00zZi95dG9DQVJySVVBb3cKEHyptPsntjr+WZhQVQadaSb0bFVq/fXS
            X6ZNICJGAasRExBWXhBDC03yqrgs2i4RyGUPnQNst+9VTWKS9J6m3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T15:24:54Z"
    mac: ENC[AES256_GCM,data:tLccpZ1t0pq57nEMKI5yBOtxtzUZ5vrrgUOmCIFGNZ93CR+z5PpEGhCOyGPn6CI+gafJuH2TDOAkVkqzK9A8UYYnMhfEZQDRYC+9DgOdpfieV5+8BAlCJS8D3D4qu5Pv9IJpX+vEZKHAKs+t8hQzCP1Mj4dPZ+x6bj4fzhxy6ko=,iv:Kebkp+fwXStlYoMP9JMs8MWy+aazq+XaPSm35xJsraE=,tag:titfbJm2UFR0lX6d6irM8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
