apiVersion: ENC[AES256_GCM,data:vbE=,iv:y+aIz8kNZGOIlVszUSHlcHm1kRZgS7fsMxvgEP/jr1A=,tag:xvPq8NaCjBfA/iSE2OXh9w==,type:str]
kind: ENC[AES256_GCM,data:gHhSUL4n,iv:K2T3peolGYi3hFyUjxnorSWncU6F1VF4CY3RhJwNP2o=,tag:w0/uVsMjXt6jEu8oayEAsw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lTgwxScrEJuZ/sIkJTVx5w==,iv:SNKTFXUP/TVFe2oy4STNsVIk6ynoti+oAYYWvOulKmY=,tag:8T8MpBKhaw+NGrvanYuK+Q==,type:str]
    namespace: ENC[AES256_GCM,data:h88qNwBf3Isp,iv:d6eL+sOWsAjXtcicnlXFWKUcsn376ZOr4B5/0Ns84mQ=,tag:uUe7BYBvcVPbfYh7s0HYYA==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:sUhzbuszXBpVdikAJGRPKAAO+9QV4tK+FIi1E3Ie3rAVSktWuiXZwQhKjifeO+4UuQYLae2NOn70tpeD0+gExxDPFSFdhoPYqkpIgxdjE9nt/tMq/GLK,iv:FED1mGOw+TM2Y7hEmJP3HSpnKgCL2EfVCS/aCllX/CU=,tag:f+wr0ExfNROe5MxHXwy0yA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:C7L6DU4O6FjqRSac8UBP7+yj/ywH99V/p5Jfqs/56dg=,iv:DWrA7RgnD/b2MVYQSUgy6DtvhIh6AFRYDPu9sz2Re/g=,tag:ndl20gK1CoO51u7MAwFi6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOUp2aXJ3eCtlbk1QMG5h
            b0laem9SK0V3OVQ2NGRWeW9QVVJGazhwVmhZClVTM0VFYmJXUnM0ckExUTVGZ1dV
            b1lXeUd6ajdPOHVEQUZiNkZMQ0hQZWMKLS0tIG1kamZmV1VIZnZpZU0xc25pbmtI
            MloyVGJwUzcvR0c4N01WemhTZEQrR1UKakkXODa/QzC3jprYxjbwRyqt+2udYMGW
            1FxepK9TPUDO0DwnEP0JmEWQ8+dzLvboi/SyK07pmlSnDHbYsTciiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T15:33:07Z"
    mac: ENC[AES256_GCM,data:Oo5TYFmjRfwttF4p1H25fu9pFa7enSBKy+r5dVqWVXDZISaD3ymTlaHYH7xm3wEL+p0N/233+Z5IAyA3ElWK6BCsqiNXxPGV+sHL0Hh05digK3YrkSTfgKU6D16q6wBY9uqdauplk8KpxotTa6AOYiyWhwvV4DEvLCfBWbEhVqc=,iv:UW6yvC0TUdKKcq1ZxWV/rSAt48Q6dvjsEUVrmXME7H8=,tag:rP6jtaGOQWDSmBmanc1kaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
