apiVersion: ENC[AES256_GCM,data:644=,iv:96uWBeOP27rSa+7kico257PIWVj7w9G6gc7Sn2D0QI8=,tag:lb4pOcEQFLVxkQuWXpey/Q==,type:str]
kind: ENC[AES256_GCM,data:ljKOUlby,iv:Rm2Exyp2NjLqouQwl3tRuAysRujPuisQEjvMfLROdlQ=,tag:uVU98cFcLxCg/vQ8Ywg7tQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qTWuQ+mItifGidDUETE=,iv:hd/GgVayvwdfMTnN9YF7GgfQ6Z0TlnNnoeR2cZkgvnA=,tag:uuNWESQIbmQglC5NFcZZmA==,type:str]
    namespace: ENC[AES256_GCM,data:0dkNZDghLA==,iv:BkBMK+qEi2pzWMSX6R4AijDMf/9Ivj/Dd5sWnSedhv8=,tag:aFxvItjM8gds9ZzxKYlbkg==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:ZzduUJIYcbva8wfadNgwnA2sCrZtHeLDiiWybZ5Zar09tVm5X3X0V4VdFYqvDSxyTXGPl5BlHw8pzdVFJcBcLA==,iv:zk42vCdJ417mCjY8DHsFF9ssbevnzbfNorhj2VpqZVI=,tag:tkTuMBYV5hAHMaGofpXdVw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:v9geMuipC+ixuk78zN7NGBYPC3uStgLtEkAQnRv/dSQ=,iv:1LGG6BSG7+FH8Yam8z01sHdONhuAWhW8VVwAd0jO38I=,tag:RU8ogXcpnnm9t4lz+UDxWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVjlCWXd0NXNvYjFvZmJE
            TU9YQmN3MzY0SEk0Q2V6RzVQckVINko1dUZNCjhHa1lKdFhCL3hXa0daRzJSa2Jx
            T1Y1VEhPMjZzc1g0dXU3NjhaenFEdDgKLS0tIE00RFVtK1Nid2tkRmRodG1yblBn
            ZWRYdlFJQ1ZRc0NXZzJraHdYaURFeUUKUBiFczIJgw2DSnkurp4OblY96bhJc7sw
            bLRopbtzNduaJF75LHHr0sszsfsU9AelGg3oXEPvNwJuGmnCSDKdrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T13:41:23Z"
    mac: ENC[AES256_GCM,data:ZrLN6n0EFR94ZCTM6FLNSZ1KowEl72ptv/KoAc+0LpLCPw1zCtWEp5AI5rHdTtJ/yIPvnzL8p/HSqn3qKqZTRE1uXJJZZAUsHujkM6PUPBpidWtcN1pe/eP7rWqiHZkBtYAtgkpwBJx3IPDWqdhGZHM4oEGrLUu2l01NCwhmtQ0=,iv:SB7IpP9ERAqsv8TVVYEwXl10OjYvcztlwK+lD+b0mbI=,tag:Vgbv9GLWV7fiGftPWru8JQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
