apiVersion: ENC[AES256_GCM,data:N0g=,iv:TiHmmjawFc/OGSoZywRdZGQftAEzNNjb2M9Jt2F0Q50=,tag:I1phc196mJwKfpH6xqMhfQ==,type:str]
kind: ENC[AES256_GCM,data:T5alg/Iu,iv:n4FnaJXgFQVtO98Uqv/VIMscIlscCbym8h/rGXGLI4I=,tag:jbI8IP8t+CIo4kKW00AtJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Nv6VHThLVA2kpdF0LqM=,iv:nbEn2WLG8VNakP6opMMRnNVvlxIGT7EhgjMCcsU3knQ=,tag:2gTziQNqZcrKgO9uBrIogg==,type:str]
    namespace: ENC[AES256_GCM,data:yhxa1IAL+g==,iv:YIIzO4IxnXxHUT9xKWU9RLyAtm5uaKk3IdAkV1KdGf4=,tag:ZQyaHNRf2JlMFzn+fr2qnw==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:8676ruApw4EdUPjxDH9o3BIgOpAgBdi9Bckqv1pVz7RUIqMbohWflqGvQ00SnTj7BKIMVe+vAe7PA1Q+F5rduQ==,iv:wfkOvoO/1LaykYe1RJTtIv70/mLRkpkYrS8jMWiYKoM=,tag:HR9uKSEVcCbj7fMz08bbSA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5GMg25o+FldPnkqngEore16nsTp1+Qdhllg23Ae7BIY=,iv:E9HUPJYzVk8hREVhHkRJ51J16Tjv3cZKVCDH2SOfnB4=,tag:Nh9h+kX/C8VpXSb1LyQEHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYXh6aTQ4OEE5b241NXpz
            a2VQeFptS0NSUTVGYVBScDhhdEdqa2w5dVFrCkg3aEJUZkxnakdXUU12bHRVeWxH
            Z1hFWXd6Ym5PckhzQ0g2eXY5ZkRtNDgKLS0tIGl4aytPYThyRVBPZWNMZ1ZEYXQw
            eUx6YzZ4aEVkR0txeC9WbzJibjh4aHMKdQ3a7H/EOmh6H8cvpP23h0wxqq8OcPuE
            KmxQKzAvt7PTijsY1a63Nmsta35deqBDwOiGtg8JUUxGCWb3FUtTHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l2j0cqvl7qv9ahx2levhr9r74sdn2ppf9fxsjhd9ey0wtrqcusaqjug4n2
    lastmodified: "2026-05-13T19:42:54Z"
    mac: ENC[AES256_GCM,data:rZrIOfgOIBAQikIGkW2okDTNPyCRcOQYtQnTdohm+uFo/BIX7pWFrug+feiHi0NFX3AiIMcxcirdMfUME6y82k7KCCsJt917q3Pfv16gXOL1tHlRIgPq0fgj0P1cQjzSAP7nkB4LIok8kamCThOJHj/heCMIYFMUPiPJNzcfO7I=,iv:QlPpCeUsPnJ9rRHf876CT1m640erssl7+9t+qh+ggh4=,tag:QYsnszsTKJOSc8+qFtwOzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
