apiVersion: ENC[AES256_GCM,data:j4A=,iv:6vxbzkQ1AhM+Tu1iajMHb3fiwANlgF5mw1WxlpDcIDg=,tag:IUcz209MLyREHzs2pM/wWA==,type:str]
kind: ENC[AES256_GCM,data:6HF4Xgxs,iv:OVqLTFLApSYzais34nd2M4toZbIB9cBrcOPKDu40YlM=,tag:lk8ql3XnIFL4Sa3PUUWS6g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XpYdr5jWocLMUcG01j8=,iv:OMaZe0aFDQBxsotpo9LPO5Mw8zkAedTMfWVmfYmBir8=,tag:tVyRLj0ARMvP8oiK73gJxA==,type:str]
    namespace: ENC[AES256_GCM,data:RkhyDbdA4g==,iv:InddZghnFzKoqMhsKmaisZlUKykGM3GqVXCocg5eem4=,tag:Y2wafB2v5wB8gFOh3S+cww==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:jlw6H48LTx5yzqExqnee+rcGOAWzZbeiNJF75mlFdC2WCDzWIg9dctwZS/2RlYyUjKKbKh1vf29Ma+ntDKhNIA==,iv:+zTzLqA6mydxSHlJPb2jClv6ZYqZcsOYp0clvFQQF38=,tag:lrY5iWzb+XTk0jyr/5aExw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3MxV90OBKbXYOQsCVA9+vX+G70zC5foUPeRtL3vTrH0=,iv:zNTs9ps2N8HiU9eD2EDfAGjSe+uj8pzuwECSvqmlHK8=,tag:I0hVEnLM7pkP8fy+VkF21g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReGdBcXdyUnZPZWpNbkY5
            NDloZ2NMM1lHaVhmc0xOdjBvNm10NmZGM0JJCmVseWx4UFhNcy9YTU1mUjFyeER0
            VnM1YllOek9zNUpsTk0rSERzQ3BiRk0KLS0tICtsUUxOTUlsbkJGZ2VOb1hSbG40
            dVNhOHdEUmJsdG54amlVcVpRK2wxa0kKJQcHHdRppX0ZbLoEYiQDtBuaeFtNVFMo
            GmYPKVG8EZQrlsmefuGkyQRsVWayofuqV5dvZOOAgSQxABw3iHLGag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T09:49:50Z"
    mac: ENC[AES256_GCM,data:bn7j6d0VYqtcDAf7xYWO0ld0fNzyAGxJU8DAe6ciI4oWKiWozAWV49j1eIjTjbS8+DxLpgF65o1eiwlxKbT1metxY+AsV8F9r24msAjc4xy2bHrlvAg1ptu1TYYnKCZ/cHUZ42uIbrLBeu6/MkVKiVFXlzEH4vgGvKW2L3Tkcp0=,iv:H0Y6v/rABccIyfesve+oUES5D7NBdshIaZECo4qLmLI=,tag:raxchNdzpjz8nEH5rh4PXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
