apiVersion: ENC[AES256_GCM,data:cXw=,iv:UnF+pPE4udqoy+JgyAUjZiH2cIH6OZrigBjCYmVzymk=,tag:LWLWml3WM0u+Ee4e6a1T2w==,type:str]
kind: ENC[AES256_GCM,data:OBrCd43+,iv:WLxG4eZUWec8RWrVxfVKWhHW9f343iowfl2wUv1jiys=,tag:QiD8+ErCpO7X45OKDvkIWQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ASByCUeBBwhgXC16,iv:q52iJ0jtNi9DvVehuTgaZ5t6GssP1bBNk0seoQqQRzE=,tag:UNZPISQPF9BMDp51SXguXw==,type:str]
    namespace: ENC[AES256_GCM,data:YuDlqxo=,iv:qiuMAwZq9PW+2qsi/A0skNqfTgpHFVvOxEvCI6K4MTg=,tag:RgnvInRY34Ut2is1ZlRzhA==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Auox2G1FRcCpMMq4q7QsE+TfjK5h6l9Oo9l+6Z1lNuNP5aFZwb1OF/XJrE/dckTvpH0zmNWLcRzG2NIb35K8zpy7Go3QEPjWsd4uNd5gFYqDr9iLPejYJSRFdB1XnXIKe/ebeJQ=,iv:6JyNzULK6A3bAso2dfiBBBmIvKg71Fy/uYr/w9sXEqE=,tag:CCwWe5TV8OGW4mXPw7rbvA==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:oJ4AFit9ONcfrekuqECBnOBGex6Lhh6VzV6BoH7/YMdq0+jzJ/6mF89Kd0OLgdfw,iv:eBHlOg0PIesSjQOQWfU0BAUEVJcXsA0x2+9PLJSmbvY=,tag:0vbFTs9Q7t5aJZb2V7Z0Ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYURlcythU0IzOEFWeXVl
            NjdoUzFITjRyYmdvVVFBTnh5eUxoZDZFR1hVCmRkNDB6YWt6K01uRVJsTm1Wcy9O
            Mk9HRXdVTk5yUWFvdmVkRndncDVuVDQKLS0tIFV2TGEwMXRlQjdxeGtRYWVFaWd1
            SlptS2VaRnNWWFA4WVU2eG1KalRackkK24yzuMe3TnNHiX5cUNzwRe9Vl08Whbec
            KrtGxaWQix9SqrCEt1uI+U11l32xDwSQL/8Z7QvjFfTp47GYOO79ig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-24T09:33:30Z"
    mac: ENC[AES256_GCM,data:obIJluzkM3gt7pu3lXkl+7J3zCqRShIM8GOg022OZESI1Jkp98jDrXIiLPlQ3DFvFfYF/uxayoybmbyehm5/4LotncXmtcyPZN56BDfYebEc4/suWrSZTELMw9QY1wmjaI3/040RZPGekDYuT010rebqPvbBDi8YCvjg/TeGzNk=,iv:ebCz+nt54pDoBRw+tco9Dr8P+5PviiA0Cqe9OacPG+M=,tag:9l5+51N/XqDn/sFWZ2DjZw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
