apiVersion: ENC[AES256_GCM,data:rXM=,iv:JUq4mhwa+6dh44WJyWc979zP7JW37Jk67h1VajlBLqU=,tag:IACdQThr8KLJu4sMPvycKw==,type:str]
kind: ENC[AES256_GCM,data:Yid1ZYa0,iv:OKL6Xlm0O3Cu7YsTpfj5ooW6ATlbJreZpk7LMa0k8YI=,tag:ZvXldCszgSB98ygy7sAPBQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Mu25RtCFCPtgqN68oAkWz27tS0Y2,iv:FBYbxfJG/y15RwutW1mdmz1xN4trWxZuuRBP1oIWoX4=,tag:Z9OtQ1PAD3IdaXbw+aseWg==,type:str]
    namespace: ENC[AES256_GCM,data:pzUdXvA=,iv:2YmLumDa+0CfRE9aGKI0nGQvEquoq9ktDIaQ4WuHY7o=,tag:SKPH3FcoSVcG5Q4ZSyteMg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:U7l6ayY=,iv:4RAbqMzrD2W9+ImyRhqslcQK8TaJgz0RG5dXeH1pvkQ=,tag:fIOv4RARkISuIoZxVbj2JA==,type:str]
    password: ENC[AES256_GCM,data:4549DeHaqQcBHNcF6aQaEMNbOA4LkAgM,iv:s4xu/7loIHvSUO3FPPiDUIYmaZpeTFP5/dMbBquwcRs=,tag:zWGrGcc4h3K+zDZ0WvXEAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNGkrSnFTTXZMVG1OdGRi
            aEQ5bEs4WlU3aXlMblhrZWl0c1hidWlGUXdZCkZKLzIyYmp0d2c0YU5ha0Yrenhw
            SkJ3ZUQzMytncTZoVVQvQi9jejNYN3cKLS0tIHBiTEpDQjlQQitFdUYrTmx4NnlG
            aDZaRVBiRGdsN2VVc1EzeXJFV0dzaWMKljIpiQXEUJ9G5AjgDsSav35yp4frBCV/
            G+dKJ2S3tKQy7vQUcCTXA5feBz3PMZPMLjQ5p9ff9FYShD9fm6a8hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-24T10:16:19Z"
    mac: ENC[AES256_GCM,data:o/FvCkpie3ztW0hnNEYOTgb7lxjfdPYbbudKOchFc1ZlIplEjfMT+0eSmLBYMFnDYmY7BMiYPEfEL4ifrGLdpd+epcmCiPgm1ct6u0z/CSM066YnniYU1LVGNtB39WUadsyoeTaWKgxBKi6/hbJ9yfgWOJglcbvkHVeTMa7i+QE=,iv:Kg6iPKu+jUnaDqIHRrmZp964YVZ3Ns7S3ItOtSSh5rE=,tag:Gfg/2DGOPcBsSXE7Gujo/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
