apiVersion: ENC[AES256_GCM,data:FfY=,iv:T3BN6iERkGJdOqCPej7WWAHprBy0nyvuAbn6n3RHKS0=,tag:N7reyEA3w7XrKweWGuqNfw==,type:str]
kind: ENC[AES256_GCM,data:SECzxG9x,iv:yGlzgJB+65v32uuNymdXIOgy53WgqA8LvApSAtOhkT0=,tag:Wy38+ECsbHBLS82m4R1X/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HFWOres3JMwNkh11RJiG0u7lZ9M=,iv:b5DMoUQYOyET6Mf/iQpiUnPLJCoPlblkkO6tMVcoDok=,tag:0qepYZRLDqPNt3ChChb/ew==,type:str]
    namespace: ENC[AES256_GCM,data:tX/zGDOfd4Ii0A==,iv:SqdafGUWuhW5DoF/h7AUWwk0/VrUO9m3MxDWlzbdZtc=,tag:dcg1bnIQAPdZLqGZ2KLH7Q==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:lVTurGm6b0N9FVLxMMW/fl5jwIBK8vsIrjnbEEA/Af8=,iv:zfzCJ/nlghsm5ouQbv8WXTqKoJ3fwa1fhydV4Hpx4Y0=,tag:wjZKVXhYseMAnKC5ThYFyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOG14ZkRLVmtNYjAzUmVM
            VkZjSFBIUHUyeE84NzlkMGdab3IvK3lrSjFNCk5CcUgwUC9sMSsxOW9UVlFib3la
            cUhqQ0FXSnFRNmQrenhqekVXY1IrT3cKLS0tIDdHS21rdWlBOHFVcitZSXU2NW5Y
            NlUycmpvQ2Nwd0taWHpaMFNQM1o1TUkKwe2i4nZxEKJrCz1UEtKBbbQm7xNd1DN4
            irRIgor3+eEPfKvHA0HiBV3NISJgMt90OuTFzlrQ/LC/nGJwEyU8Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T13:41:23Z"
    mac: ENC[AES256_GCM,data:t+UC3Vg4/tyEyn19p4isR83h4sWVxsNH6vsgLGr7PcGj3MOu+KRPVfg1tAIMtoeu25aRpYRVQhGDdW1Bx/JUDmX//SdDo0VEAeMs2+tQS8LQt7IRUZOFHV45Py2pbTJ3qzbuW7x614y1WzlDSASNw8788pPR5c5JMnUBaye7JDA=,iv:0VV08aK83+nnGRlaQ8pv2pKWkueTeyeqW+dNZkeyU1Q=,tag:a66i+WcYC6+qkbl3rolVSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
