apiVersion: ENC[AES256_GCM,data:FCE=,iv:PvMowII1txPiY30NSsE2sYbwN+c96IIkMMW+fBpgfe0=,tag:iuc+DfVKe31hGRYMDhOJTw==,type:str]
kind: ENC[AES256_GCM,data:EAaBhFYJ,iv:SLosZqjuWNU78NBLt/SgQGtyr/RR2kprtPxNQGXkUj0=,tag:85ePGdzzQlHhhwRHqf1rJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AzfWujAoIyRIG51xdbslzX/SPgE=,iv:uM4SdvfWa5gk9o+B0IXvCM6Fb6xFEhHtG1ntddfvzac=,tag:UpwbuCtWNnlg2Ee0F8O0EQ==,type:str]
    namespace: ENC[AES256_GCM,data:rtKWopRsQwxvUg==,iv:/AzNH6IyOpWbubHqkoOm3GvizmbzTGmfVwUZtHv7250=,tag:zc/9SmgMwWjQzxTbnDgYXA==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:YnmVbDTItNvWBs279hOb/a9RRUlybVl1O/iXwpYuIuE=,iv:/MjjIY/ih6MrgkxSItqurPDUjzf5Wb/hlUu1JSEEtmE=,tag:tokdO0W/LO4NnYYNKAlecg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ME4rbHkxaHUzL3RIQVBr
            UWJ1OUlqSExoRFFmd2l0bjF2WTdwdFVVL1gwCkRoT1BLRXd2dzZ1cmJ2Ui9NREV6
            a2R5aFFTMGZBQjBnUC9OV1ZsemxZRHcKLS0tIFBvUmUxVGE2alF6RjI0R3VRbWl4
            WHZYMkxJejliTWxjY3RUZW5EQW1CN00Kejy9qniTIWQGNxPEnhz9vix8dR/x5zYq
            XQAJ8cqxvvSpcVV0afPsl0n9S54kmGY41b75n6yUNUgSi42hye8h7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T09:49:50Z"
    mac: ENC[AES256_GCM,data:KRRM3mH88s0+4zmo440lpX4MHrGYqkgiYA5VAjyBYttxWc2EPEbxuRrCLhKyASG505M24nfchHHCkiqneEiCPdaF3Av9kTkwZ5sNCdTIcQH+XA8W04StEPilUSr6uiMbm1BUznAPNMoJnw1JYU2ksZyTxgMPjzF/n5Gy0n8LctE=,iv:oi31gKl9/FslWRj0jEqxiWLmdytxmnxwp9kN1qwl79U=,tag:tq5Y06wh5i+J4pgfKL0w8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
