apiVersion: ENC[AES256_GCM,data:dvc=,iv:ls5CUs21tFBZHF4MhFxu/6USalf8PLOw4mA5952JSLE=,tag:HVv53Fk9wQ7fZ5GtPMImrg==,type:str]
kind: ENC[AES256_GCM,data:+3bSYVni,iv:+zj6tvcpxYIQJaUo0NMzxzunI4ZYFWW8bUK7OR8zAgY=,tag:ldlRmoQhUCaWj6lgPosJVw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s983PTme//9R0MiDNe2X3oLFTtA=,iv:SqFk7rli5mhw/Zvly3U2PmU4TI9dVSi8hHI87C/X1No=,tag:mM0XJT6zS8qoPj7hwe8c5Q==,type:str]
    namespace: ENC[AES256_GCM,data:RQsSK6NJQBu9aw==,iv:yEvWrkz0J5R1swqZ9pVwV2cK3tO/YXQ35l4viEi+iUg=,tag:6MBr0F6Rj0JTpUJXUu4aYQ==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:vFyM4AFn4L6J/XdpanHYCBqk4cn2HPGJfvsCoZ7Id7A=,iv:G5jUWQDJWG2eUXMDk7uoCR0287zhrqcVQkYROkIix9M=,tag:KtjPtFcj3N5oZkCGAIC3gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUVlCWXRvVUV3ZUFyMVl5
            ZXVCaW9hR2dNdGlwbzNUWHA4QS92dDdxNUY4Ckp4OGJNMGppYm1Kb0kxUEhhVEFU
            MC9PejhXSFVpbHdaKzV0enVQeEluQjgKLS0tIG9MZkg4S0ZHTFowNldiNnA3TUhO
            Zm1vRUw0c0dzNGZycmdzUlhRVVJ1YzQKJnOfCmiBxEO0f7huvCZLdor2Msouac1q
            v0Vhk4bkQOL652nzFUJ4zWFIFbFc3Q7u/EWP/BwumgcLAKJhCt8H1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-18T14:29:18Z"
    mac: ENC[AES256_GCM,data:Gma+mioSQilO9JwSdGgAFzl7EYSXy88+wo7xV3AkZZzlPmxaUZ8wekRhPgpygmiGe5EaZZMhWhVgi1DDaPxmcH5kNTOz/+zDuBHpxZcSyYx8aQDd4OHr2s2yKlpd+Wb/aPA1ieZhkGA8+2FfWsEpTgzIlqKAeUAta8TR9oFnlBk=,iv:giKaQq+g5wA8Nz5B+tY3f/tQJBdM6d5kmBhpnGXBYUw=,tag:2MPfbEbdDD0Lt8uAEN/05g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
