apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: searxng
data:
  settings.yml: |
    use_default_settings: true

    general:
      debug: false
      instance_name: "SearXNG"

    search:
      safe_search: 0
      autocomplete: "duckduckgo"
      default_lang: "auto"
      formats:
        - html
        - json

    server:
      base_url: https://search.home.didcot/
      bind_address: "0.0.0.0"
      port: 8080
      limiter: false
      public_instance: false
      image_proxy: false
      method: "GET"

    ui:
      default_theme: simple
      search_on_category_select: true

    outgoing:
      request_timeout: 4.0
      enable_http2: true
