apiVersion: ENC[AES256_GCM,data:q2E=,iv:V0vSjKT8t+lexrFGj+LjCkdzjvPtdpCPQtpxoFexQi4=,tag:dZBrbnfACsaktBxPwTwofw==,type:str]
kind: ENC[AES256_GCM,data:91WEvzFV,iv:uqaHOi3I4D+LNziA2JsfYkqCHFTHLh60oTz/rRznxs4=,tag:quV+NH+3BLp3bfJkxQIxeA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aMKOP+qIojIa/A74Cu4=,iv:DV/rqq/ykydBblTE7+CD5/dnMz086LiEujWb3Jg8XUs=,tag:84fbknnIPDC7GmnIlxPmIw==,type:str]
    namespace: ENC[AES256_GCM,data:PiBe47uJJA==,iv:qkB9VPNUKTZPCm617KFWn+UHadLNjIklguV8bewiJpw=,tag:5MF9yOCMJWeXWfXCSwWd2Q==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:eAuI22SSRwMrnuDrC7QOPDSUvNpHzGW+dToF6TCAV5KMBGnokDa65ehbpFRfQ2trlxwcpfN8wHV94r4fsBOBHg==,iv:/GkiLaJaz49AHrGxDiuK3CSams+Uppgvual+haW1NXE=,tag:01E3KbI0R7U9zhlVNhveew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNHN2TitQcHA5UjBocVYw
            cVNYY2RUelIwY1V1VVhRSlY2RlB2bjhYWUdvCnlmakpZVXZiK0xvclB0RElLdEhB
            OWxSdzJzbE93OTBYRzJiZmFTbFMwOUEKLS0tIHFpYUp3THRVMmhseTE3ZG5SZi9z
            RmRJQlY1WFdkcm4yZ1p2NWJFOWFySUEKJ/dMipmzEK2sMAznI9rgOEzkF/a0dNn7
            I6ponuFA0BeVrzVkVs238WZlFynO+K+Q5DKzjf1NjcJmJPb+vIxskQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T11:07:11Z"
    mac: ENC[AES256_GCM,data:O3L07OtvDPsLFStOrsACvl8u3R8WAk+iW57T4UBm7cYP5W1JhTkHJg0JbU8DrCZMr3n/yUgagndkA4EeyTL13sC2tF6ulCCGgOyiC039Diq5uppsR4ov/fsd8cVv+O5VNewXKu0ATKyhxoN27Bg2zhOAxQ8BQtKKlruDRNKutOE=,iv:54B3GhZvBrDjE+PFX3Zm3/9YzZ8F4+d+/ZjGSb2pOoE=,tag:AQES1qvo5itotOaLbCheXw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
