apiVersion: ENC[AES256_GCM,data:2cM=,iv:j/50LfWtPgfqQLInQB8g1NqlsUF9x3RtizcC30AjJ/M=,tag:1pvYLv0/dv16KUG2gJQIMw==,type:str]
kind: ENC[AES256_GCM,data:KebOxEwz,iv:ezjxeY9IArWrN1o5wCNacQCRV1tPOwqCKygWGBQyNh4=,tag:Cdr5JxTQaUevrtlo4pDtBQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IOk+Stq8ATbP7n2WBpE=,iv:/M4kjRCLOg2x+ZHwbZ7TCf3TAtFOGneYH+GrYYf2qhg=,tag:t5dgrUYy+POTDK7nDQpejg==,type:str]
    namespace: ENC[AES256_GCM,data:/TRJcebW8A==,iv:dYAt3hqaNXWfKtHkZUp3DOySR6/DVdeM9+bq8cWNSOg=,tag:ETWRfL4zKd9YDsKL1llzMw==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:1WybAiPZY12Z4H62Tef8QyXxupdFOwFgLbx0AQt8wMxYoqBAQZxKzgqQ7m8S5T3uFTFvmeUTh0Z7Lwn32yYb8w==,iv:1gGAZSknv9kj9T/EIVfe9R0V6dZnRW/3Nx0Y5SElSwE=,tag:iPRxPMrOYBDW/IsW1Il/fA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QVVlZzF4aXJBQUpjWVBr
            K082aTVSREQ4YkNqRk9EdDVORmVGc3JoVmo4CjVRNmprTmQ1azgzOUx2YnBxajR2
            NnZBRTQ0ckRTUk5NWWltUEkvL0IzK00KLS0tIHkveUpSSnNRYWllNFp3NUtpZEhN
            L0wzS25tMkVHeHFVN09MUXBDT3piNnMKHYUsBkAOcTPaLj4SOHW1R5WCdELy7V4/
            mUAF456Yguu7Vx57aMWWgmpXEC5PnHNR+ZMFpweqigA0wqRViB3J/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-16T07:57:28Z"
    mac: ENC[AES256_GCM,data:b/DS3ygY5E1xb2dNbwRrG8JwpVwYjC/wmNDYJFDM8oO6joRiT8cyZazbbsFPJK4k6dJupIhNHY5WVrDan/pUZeag7LiQlOYKi3uqHyZUGMycP8A7A4l1SdeNVzh5eV+P8un/VjHmbPkb378U0ER+FCdri/4i8OGBCXfjOLpOcPU=,iv:N1xhI6uyAJuRFgjnM6uFwAr8S/S4UG7Cv3qwtqmaWp4=,tag:GqjnX3jTbj1SlR06MJtkcA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
