apiVersion: ENC[AES256_GCM,data:Tdo=,iv:sqeV9SRKvIDA1Zs9gVqrAY6BXXF2sjVNhYuKdf7P5eg=,tag:U+F0peU2SSQzxYyvVRrDZQ==,type:str]
kind: ENC[AES256_GCM,data:1LDkm3c4,iv:Kei+VTStWVC2ekx1tSBZ3bctxFZqYfg5NVdH9BJBhgs=,tag:zwS+g/yITGiw76VN7zMiAw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iBD99JctWbIBBCHz3dw=,iv:GXEe4d6e23tEGyqQMUZO7Dk9hrzro21joSj8/zcyRf8=,tag:wAvx1HTVWZeyqzdxgAe51w==,type:str]
    namespace: ENC[AES256_GCM,data:pgk3go0gQw==,iv:4hCUz3U1rqv+FUgEhFl5dGTDwHm6SXsqFRFrtQRLD1A=,tag:1BjV0oErFRMM3jgpWEF/rg==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:PY9uW1KINS/xM1+na2386YjUrLrY2D9vS1a/n2z7vDtJKiQt//PsKDmDfm67/WZzGVwIwO6qo5VQJzSAdjxCTw==,iv:+qOxD7rjAh1Z4pBxkhibJRIGsweEwLt1OWhJxisBCvE=,tag:EriqaQsSiia1JTUTaflstA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVGxPMXlkQ1cvcWUvSnZ1
            cmdHSG8rTWVTaytza3NkbFNzL08zbi83MTJZCnpLTjFJSVNNSTI4MVduWmFkaWJD
            bEIrRE9vWERxOFd1Y2xEMWpHWDVkUnMKLS0tIHZ0REI0Z1k5WEZCT2N4K1gzRkZZ
            QnJNdFRqSTJabmQrQWZVOXYrd3poQ3MKHhKKs2ogmO0So4wkuFofRlmc9BtqD9wM
            eSA0UhPYrxhdLF8CydgvlUwn/cMwgb1tJ/6sSLQXmf14JckT7WbFmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T13:41:23Z"
    mac: ENC[AES256_GCM,data:CgXyoic0ie7CS7kmR4CLDo2W0oCdDtMxV9glY4YxWXX7xFhw+ZgMXCQ0TwaNH3VB5qHKeGAy/RtvG+mVIdthG+UQWf/3VAkhvWdTeaC9+IhdTjG52GHeKa+ek6WZ54O0p2Q1LymwcBswIcSRqaNsV6Fr+pZm86Gb4mFAOETz7bg=,iv:tqn4YRtRsYUAoDK8mryCbHfotQwrK7uayp0YRrL4Ukk=,tag:UkbPyjDbj5m3JKABoTtcYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
