apiVersion: ENC[AES256_GCM,data:+rQ=,iv:+TNCmXhi3VCDtDNoUIDiJgA7yosYqLFKwquylFGQnn0=,tag:/N8reROODQ4GPAa5K+wTUw==,type:str]
kind: ENC[AES256_GCM,data:X9wNj6XS,iv:hLqI4Q6uVLf/kuNeG0gbyp7kESjMJgY1xdB9fZaCqp4=,tag:ZSrDBB+bu4vsew8RjHkBHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZDeaaNskrQXxB97jXvI9Qw0owA==,iv:Cxt+8aOGhZ4tckVB/rM/MxkKoE/1GNTiwqVVg3vqmWE=,tag:dlBVhXHtVZ0kbmh/ZLp4NQ==,type:str]
    namespace: ENC[AES256_GCM,data:YtbCdyhGHMUYTX8M,iv:MHI8h/75P8FziKJ1uwrmNyXej5cuRefkIAdUKCppKXw=,tag:YGhpNUW22RxZY9rouzc0mA==,type:str]
stringData:
    DASHBOARD_CREDENTIAL: ENC[AES256_GCM,data:3dOFO1Mw7DkcWkuA6fU7RhVuRP2LheW33XSyqAeg,iv:vKbpE5kPrp+DCJurCg3VvV2gQD1HcPUoPuFRocI0tOo=,tag:e7wsjbk70ZjVg/HDi50a8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYN0RONUpxQTVWakdLdDRi
            aXYycERkNnZqRGF5N05LRmpqS0E3SXhlaEZVCkRvQUxQOGg5TDFiSjhIY25KRWlQ
            dlNLanNSTlVCV3VIRE40OUpzZEVMUkkKLS0tIGhKTDJpT1g2V1B2TDRwQnNGczl3
            bzRROTR1Z0JZaFlpd1IwUXV5OFgxNUkK9hiw81pkmF70KjzHorgqYyMeuCDYeRDS
            tlOeRZHDXjvSSpZg2LjO51s2cifs6Gtmt8115zmC92mPv2WWY/Tyqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T16:12:51Z"
    mac: ENC[AES256_GCM,data:eoqODou8ssLH8Kg1y3MW/B8XxRvDU3cdOYLx3SW3qtg4vG4VycSbV/fVgfOYLEa7Xz/FD5DuTN8JXKInIEFL4uj7oITKxLuTW0MdFUVMGfDssciyIITNeB7Ha+qYXaJkHGr1jw54aDKaMSx81WxPmSsIa+p3JmrB8f9Jw7b2HQA=,iv:v7byj/ZURsF5awHo2NVL+yhDgUjv+m1LHUWz8upDAR0=,tag:bWN99t0akhqymlwFGt8dvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
