apiVersion: ENC[AES256_GCM,data:/sY=,iv:3yJfCP3Q62cVNoWWH2qs6MbkZv0B6jDpKyu6jhp40J0=,tag:/C7dASjmgJWTkEwV5N1Vhg==,type:str]
kind: ENC[AES256_GCM,data:3q//BnLQ,iv:pwGUiQSFJ+V5/zpAMRztNINGVgxqUSw4nh8X6lSKK9s=,tag:BdGW4NlJ928PoFYXJNnzrA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Tj06cE0pCHZrkVSgWHJYP5VdXGo/YnY=,iv:5t73OZXKnMkOs8zjhvCI8He90vPEHelI7HZpLMIc+mo=,tag:ag0tdzro2ErJ2JW4fk+qRg==,type:str]
    namespace: ENC[AES256_GCM,data:8FJCzlm3e9f24oWA,iv:KFel8Oh11gkkodeuG82TpqCoHa4SN3FlXdxCYOtMMQE=,tag:2Gw8+JxkFYlwg42YoocQGg==,type:str]
data:
    users: ENC[AES256_GCM,data:2UOknO9pUgH/BwYx03340BzjqhTrZcxqSIBv755ecLMu5X5GqkPJ5zVxe8alCyAzeW+DOGxmnKSnxSjg,iv:aiWZMUgihctPgYyxLQsQx5+9He8PeZ9JBcy7xH5BYy0=,tag:qNyDKessWtT45LCDpuKuRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYzFsTVhqUjlmUjYzQ0s0
            OU9UTFhYYzFRNnNOclU1dTBQWjkyTmNJeDFrCmcrWDAxVUt6dnk0bWRqNXJqV2JZ
            L0tHYTRSbzdueWZGQ1l6eVRuTHhPMmcKLS0tIG9sdy9aNlJMYzJ3QjY3dHFZWFBC
            UVZ0bXh4a2NRQlJKdmRTOXhIU0RFNjgKKmrezI2+sV620skIP1ho/BoDqx1tvfFE
            Vrr17kw9TllyxkFQWjm0G03LUEa+wOuMQCQ2LQfevp0F/W87R79vQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:40:01Z"
    mac: ENC[AES256_GCM,data:1bTEEcxVBQEWqe0bKYAs9BCe10b/UcXkw9z/oslUt4wXtVTSqa0BgRpwQpo4RQslQGLwt0aiah1CPFBpTnUZfxx+2FWD7zsrDDVN5+V+QtvLugv/uxEVcSbbdBzNX7nVcrjMoYJ+d6jIMaXGHShug3Lx9s3dtTO1MuC/hJf9d0I=,iv:fEKQE8dFpcLsCdFRq+PKBI/k3eNJzE2PVqYu51pZnmw=,tag:Wj+/KWnfpOOKeiy01fyfQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
