apiVersion: ENC[AES256_GCM,data:sWw=,iv:6zyXnUoqHs1v31kFO2mwAoIKZ6+S1+bqJ8UxW2EM/TI=,tag:+jO8qWW/CcA4hrnTKga81Q==,type:str]
kind: ENC[AES256_GCM,data:Hs7yjyFw,iv:2uBBR+aK8b77w2GAMkxh9zzbOQ6XmuykG1HChUuNZVA=,tag:tfb+s7h2VK5UW/c06XIyfg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ugQQblm44oYCuOPP5aQC5RlVuA==,iv:OSoqSaFi7Q+t+AfF5CMPhsRvX1FQI3Tpz/Xa8Sn4R8w=,tag:qCZbYJ+fkU48BHFYlL0IbA==,type:str]
    namespace: ENC[AES256_GCM,data:/eaC1uR1mc7E78EJ,iv:N9RRrUYBUBSSFy3NfA7gEOkF8yd9doXzfsOlBUGrxDI=,tag:2K58JWsvXEngtrC5IXoU6Q==,type:str]
stringData:
    DASHBOARD_CREDENTIAL: ENC[AES256_GCM,data:fv9zeu6IsYImsNKURMp5boWJv03uDll3OQT9fbM=,iv:pIyOxV0TH+s+dmBCuBYr9Up/Tc7sx/h4S8wwE+bjt6s=,tag:cbLCUo99tzDpBCgYDRoZMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUWMyTlc5eTVueXFaNXQz
            Y2Q2MzllUmt1ZXFYVS9DYW9vQkQraCt1YnkwCkdCYXpUTkMycmRjSGNRY1BtVmVn
            VjJEbHBGak5kVU1ZUGtaTjhidm56RXMKLS0tIG9OVStaRjZXLzZvKzdkdjQ1THlk
            c2J2QTA1cjZ0TkUrdURXeGdlTDNoN1EKfysOtfJ5o7UWoN1jVHqGapbSk3JHbSh6
            elF8jqn8rUVEeUUdaUX/xO6uQ/tZR/ePnKTGJx5aUr2ZXZuWkghVlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T22:01:10Z"
    mac: ENC[AES256_GCM,data:q5haiBtgTCaN+QprAf+X3Iij9DVcsq/nqEhfjwx1IthAtmIkwLCAUv02+kqlTyCddOSZx9KiL5FxU7C0dyHoRZiM0dSHlDng5oGGiHhZ4dqMzRTLxagSX3Pw+moK1euStM7446pmOcRwh4QlxTZLZ8mOVPe8KTAmt7lgDXWKWHk=,iv:DNy3TsVjRSJ6La7jXa449MQG0/rGVuEsUt3OBUj0y3E=,tag:QqoY3lK7lwXu3AfAQMeJWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
