apiVersion: ENC[AES256_GCM,data:rhQ=,iv:zCmUJ+YUOJmFoyo2z56tsBL0YVafcL7Gvzid9G831a8=,tag:ZwuF47qnANn3l7z1hDAJrw==,type:str]
kind: ENC[AES256_GCM,data:Jxtcee8/,iv:fJvnJbv2V2uZEtLB7D5uTa6iDVpIlV8XkOToMz7Zkb4=,tag:mBALlndFKBeCcxm3Fdv1qQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hn4olSBlnElWsbN0/5lZ7A==,iv:sEXoRSY2kiqA31K619zgkhYYHJEWvfDYObtjbsrltjM=,tag:Fs++3ECgtNSPOoXSSB6D2g==,type:str]
    namespace: ENC[AES256_GCM,data:8Ceq9hZxsc+f4ZBR,iv:vTwReDzGJOGyWxo6L+F/qUT6BD71Opfzte1ADL3o7kk=,tag:EbYJLpojO7S/wuAMAw60Cw==,type:str]
stringData:
    id_ed25519: ENC[AES256_GCM,data:LBp10ldyIW/9/PDQufKPz0gUnqxQ6z8r5j3uLaNhTlF7TQT2y/WOkSUwJaTwW9eM3LuQ6LLQ7H9ORFqDK+0hMKZ+h35bwCODl3rNxoaPdRfESvttvsBcA+1b94E1C/48EZ998cwACSRMPKpHKB83YXRiRC6T29tcTELi3zj/lBSZjUadILebO85C7NTAvTbCHPGhyKLNjajHYQ9EiFme5AcPdQZV6pdraV7bPnI316Tk6rNPkWcxvUvG2SESTyryAuVbDvGWu0TaaL56USCDHGa8NMqMXp3PXs8Shj6+J5JaXMxQbS4ccUkPoYLnO5N1eFfnK1SlNt4xeXcf1ptU8ET6KivzfVfPfyDAnFSa45I/s6+Afb17prSBHIOc1moWhYRU2WXC0mi9o8CHXSKr1zfbT2sMa4YCOpWUJ+p1ReCxrOA+UWJ+J1Z5mNVRj0Tz8BfVv4/eo7pIlQ32wGJ/8odFXJnIguaBUO/8jeqqwW0FFuJFaktnsgQPdQl4rHjwmmj6opfB41h37XRsU52uaZGBeVUsh9P5eWnT,iv:ljiz+wasuWu3rmklrNbzxQBFcLs1d7bkH7hFV3k8ISU=,tag:KFFTR+MeWlbj8GLb44jskw==,type:str]
    config: ENC[AES256_GCM,data:azZKO3uU+Mf7DHcwwqJgvdR4UbeBzLOyhVHy5CeJK0dEX7079WA+ftRI1IPjtzvrfn/UjG5nN4KnYvEvy82afwGNUWiAsQcZ4Pf4dhqF8k1ImtD9/obT1oSlyUf4AbFpgNmXwgYtQDDg9eU7yhIAfyWfbv0xHNBR2Zki5AnlyhJdvXaqEp35VLw1XY3ULa/NkyCLKZ5g3o3NbQEDP7oR7eNbCupJIaLoVleyVyjg1IGAfDB6RN6dR8TBGDMBPLHlsQISj3BnNw/2Yqb3mObSu2psx6Ot3OD297KN3rzr6HwEQ0FALTDuZ4roCIcEBO/RLsGh8Htn/RGhOOuQytLX+9Tp4fsrLLWceULla5blgZoSmcEThAOIbNd0YDuPJupnRTLWw221+4w2gpXz6nBwLNB5raXacpJmsDGnPraxwIsLOB9CfKpXDQPlMezNpUtw8vY1w2/VagwofVIJ/YS2Q+v4m2hy/pXZww==,iv:4MxItuxL08jrW/BPFAbJQcbl7wMdkUt0WYZVVrjKJfU=,tag:QWo354CvQXatte9uVFayrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZiswM2ZHb2NJZXBTU2pJ
            ZTQ0dHVxR3RIRG92WFY0RjVSMlJKYlByR3pFCkY2Umg3R2I0TTZ1TXR6dEJuY0VJ
            c1hHQ2FNMTdXM3lQS2RiL0NiNVdCeUEKLS0tIEdUSzFjcVYzT0wrV0dOaW4yWHZU
            aUx5YmIyTVg5RnAzRGExYXVBUHR1RTAK3xi69fFOmCnV4qUzdwhWfBf4XnM80iL4
            Mu64KNiNmHDxdHlN6mgD//qWUmWLd5ptQh3Xuk6inRJnEVXjTemuzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T17:13:50Z"
    mac: ENC[AES256_GCM,data:C8XOBzVgeTCWTN1KZfyHcJV6L3AjpB2YnOIPm8XuG+WIF88JI885yiNCsjE490osCarYdvHIFvncSwclpCf6+oKuFUlBT9E+hGTWmLZejzpQ9C89gkL7aZa2GQFhzGLF0OAmdcbYZhdJMhD0VjewRC4OuARwRKDybpGxjUGfyL4=,iv:UpVqMWz5ZizV8/SWgSt4adwY2CbwQNbo7VLP38DJ5IA=,tag:WCV00MeWKTAv1Xd1lHWb9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
