apiVersion: ENC[AES256_GCM,data:r3Q=,iv:HYW2NFhqynGjQIrwKPnFKyS5e7btPo2np9FhZYxh/Q4=,tag:xL67tHE1FMxoyEPYu8BTpA==,type:str]
kind: ENC[AES256_GCM,data:8SwyjnfU,iv:XXlyXregkTZHpukY9YSGL0+8qpG7OI/Sb1s/SyTn+YM=,tag:xP5DdjEVo7w4kXujb/UQ5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d1lDrWL+YGbjgsiL9G7lLyUCzoRolw8=,iv:BXaYGEZFlHLl5Cd0S8s9Je8rFJM1EQB0ar+O87tZqps=,tag:PMjXmC7h2aKBgFwRDRoFHw==,type:str]
    namespace: ENC[AES256_GCM,data:BEQLdlGYiSNIBlcd,iv:lo5pc4CcN1vTkXFzj1aIzdIJ2TS5hqlNe5u8Hl8+Bsc=,tag:Rf0KURkTOdEesUG2UiMpxg==,type:str]
data:
    users: ENC[AES256_GCM,data:5W0AzeXXIiOVelGtUbxbLRW+mfDm472obiXQhQnBgD/ss3NgzY2Fb4kUcKtrwxrTvRYw8vN0mwXPeo2Q,iv:CJe+dDPZNZvtDVsYUDTs9aJhtlT7yJkWtyNTiXNo8/k=,tag:3LihV0Sns7FBODgFQ4G2+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQXhRVkhySytzUWVBVmY0
            TW8yYXE5eW5mcEZGRThUdVYxUFE4ZHlZQWdjCkdva1NpUXk4dW9taEV4bkFENlEv
            V0JxdmpHOUFyb1RQSEV5V2dyeVk2VGcKLS0tIFB1eE5sSFN6dUpXS01pckowaFhP
            S1ZVSjkxOHdKakkycE5wSVFXam5GSGsKX5Y2h2dQhXmbTqPqfdjUObuCxCLWOq1d
            /05+1L3wPBDB7OVorvX4veDg2tpBi+sKMGW4XdU3Ijkg+HOOxG6iQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T22:01:10Z"
    mac: ENC[AES256_GCM,data:TyB2r+RKDl4XqcheFxk+4AUdeRDfdB/ME1oB+BGPiqWzy0y+UbzrG+RTXCiQ+F6HVIXkzUbWp79iZxSp7FUhK2EbpADsu14aU108qL37GI8OO25mx42iFb2nJ3p6b+i2UFdHuEktUtBSmngseQQVkgMZwAtH0RBXh/Ch4pkFZE8=,iv:T4ukVc1Q+nJx6t228uezIaUA6c01RHG4mOjAQfKDnqs=,tag:lMjBJwY8HhZ+ib9kn9ZQFw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
