#ENC[AES256_GCM,data:ih3ctrIS6xF9lvJcy+q4GPpIA8VMpBJwwK8RaMGphy7kxqHq3WNg98n9a8F8zk71/ZTkW5gHZD03HYERb+xVXqrFoX7mhnE=,iv:2vfJIssVcCXtNsC85fkrKTDvjgrCXTqLBIBPq5TlAYU=,tag:VBzn4j51djiuxdHvaAtbKg==,type:comment]
#ENC[AES256_GCM,data:ZZGN4KuTEHtGBxgH1avT9b0EvnfTDBv4DKM2XldNgxPwgotSVaf3t0rpyrDmignXqCzVQ8TnXnv6324Hk9QrPFn7fuyYuA8O,iv:w+B4W+tu2AM9W5L9KJuPBwmWIQnEH/pON4I94NVj9cE=,tag:DpKCG/nRNQv7sKFyEvJE0A==,type:comment]
#ENC[AES256_GCM,data:IWOGBOhSm2bd87cydp1Xl93EYSoh+SB26jx5u074CTC9DqAiJfW3Aqb5xVGv5CLMudbZXA9wz5J1GfFBoA12DMp6r7a89g==,iv:SulIBDPNeI83D7l0kjxzfBo3vVinSx07l9uLqxdhdqo=,tag:zjdruBILSbwsm9xop3iO4A==,type:comment]
#ENC[AES256_GCM,data:vxVGIrIbl4yb+4lino4c0rgXbPETLTdybukTqwOeI5jXclg8Jc2EDWczFp1hR6KMXWoSYWyK30aKyH5JMRqTfbeTJ5xfABA=,iv:Iz1HtiVLFO1IhF4mUHGtImjvcK6DdkNfeUC3HHGSOrs=,tag:yTxDa833ovYg9vzI1Uy/jw==,type:comment]
#ENC[AES256_GCM,data:WXA4UEXupEiN/3Km,iv:5vyiQlnyqjqTt1Cm2N9CJJc22XPySGFDXS3N/AidYSQ=,tag:uUHdY5UGsINexsXzezH46w==,type:comment]
apiVersion: ENC[AES256_GCM,data:8i4=,iv:Vjh6HyXIza3pYwofC63N5HdpMba1xEs0XmZxf+JTLCc=,tag:Z/dBWculLpI24peu4R2gRQ==,type:str]
kind: ENC[AES256_GCM,data:1AjihzzY,iv:kUZJZvMdusjViPCnjBUGqs+x8bJcVsTJPHJSTn5JO+4=,tag:q0iEL9LmqHVHKSIdOwvD1g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yDdNCH+PjjRFJf1RGx7onaPEZXin9Nz/uQKpUAlbRbzO,iv:3iVCzAZzs8j6aTJwxn5END9IPZ4nnb2CdecCWguRYrM=,tag:UoqsYHBjdxJ5gUKxsr4oyA==,type:str]
    namespace: ENC[AES256_GCM,data:3ScQL2yk1tE9VhVF,iv:Hve/2MPwsdI5dhM7gtuP0Tz0bUNCe2tp3J4qkpIEfFU=,tag:KujEEiSILm/nYCHTeGK+Sg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:hDZUCttox/1RFcRUQF3EltMakmaZm7qu,iv:qS1u1gU5r1G2nbTxw9StgRB4rJ9vSKPFtPn+LwSoPrU=,tag:9EE2IJ9VK96/sNUaj2CY1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcWt1bHVGSE9OSVpkNUlX
            REVmMVkzSk03MTZLdGhPZVdoR0ZETGF4MnhFCmV5Z09NOG1odkxQV0RDak02UmJK
            SmtjeHAzaUltdnNvSVJQWGpjV2R5YmsKLS0tIFlGMnpOMVpRWXd3dmJGK1NkQ1Vx
            Q25QY2VLS00wdDAxNkhMSWRoMHh3RTgK545WbbPAeK1+30aR/nrsaucpgiCcKcmJ
            vqfI4ML4+kfa+o8yG6AauBlCHSOFc6zUHDF6ANbTIiW4QGpDFhXxxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:40:01Z"
    mac: ENC[AES256_GCM,data:A0F53yeZ7DeL+okCskcnM60nYMApkIaMn0Gr02fQYDGoino2Y+biyz1IGT0oELUbr24uVc7CsoUWt0FDavVhGYaUZT32JJayptzvgsWGhhQpgYsL3yOWkdJ8M3nomkFsJM770n5lT4AivSsh2R+//EUgKjRR/jrxZlCG5vYY708=,iv:rZ9f5wFJmYl8xs1exS9GP6i0Vuqmbvz0PIiVdxw5Fbw=,tag:SpOB4byVSMz1mR//Qp/beA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
