apiVersion: ENC[AES256_GCM,data:bA4=,iv:WCsT+wFPYJKebtCmkFy1s3Po0jle66/B1ehSRrQpcCk=,tag:eVISt9PmgltG8MMUQdOfSA==,type:str]
kind: ENC[AES256_GCM,data:Hz3Be2kQ,iv:9Fwr3zhB2qbNhhirCBOPsZRPJHhvfehWCY2zXdHObG0=,tag:+94lgqkXQJKHYcjOfmVrUA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iZ+0jMe23VlhdYzFlc9dhGj1LuH04X4=,iv:QxRF09W12akY8kxT3mEH0k34lsj9Ow7g3nZ7JC+G1UQ=,tag:6eLZJEo3BztLB9dxI77kkA==,type:str]
    namespace: ENC[AES256_GCM,data:PMnoj8xDFunfBy8h,iv:W2HORtDH2GZRaeee2lGFqnwl5wR4JwyVfja8ikb8keI=,tag:laNPJ99VEajPTGKfuUdwew==,type:str]
data:
    users: ENC[AES256_GCM,data:Z0P2tAMtP95MQ9GNRyeiN7hcs5eL/I9QIeksWjNxlI4CaYW7ZGlkUphjGZ1ZCfCSh80abJScyoQQ3iid,iv:bqbpJnRJ5/LamAhE7CpSB3EGCfPiXN27AluslVXRugI=,tag:sUCb1yJq8V1hDDK3RnluQQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:SeIi3dWOYUBfIot4ri5T93f45k3t6u/1,iv:aWf9WBGE8nUjJKw3kNSxWSZQC+ySjKnBgHcgtIwcXvk=,tag:tdsHJZXGzGO1VRlWbkPXsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRi83Q0dxSDZNYnVjSmJ6
            UUF0SWp0TDNndzB5OU43QkZ2UWpIOStGRFE0CitKaG40T2ZnSE50VVBqNVdRVkhN
            S3p5NVpzd281SDdDR2loNzA1NnRoakEKLS0tIHVaQVBTemJmczM2aEppUVlLTzRo
            QllhdzVGLzM5SG44aU9ibi9FSkw4UnMKwi+TZatSDZ3M7lZo5W1J5o1jRgJoNDi2
            7kFR1M8xe8k4mll9iu3f9+tY25bqgT/Nalta663wdEPDnlp3ZF1++w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:29:41Z"
    mac: ENC[AES256_GCM,data:/5RO9Hhb9f+3cobJiU6sBrVM3xa6NggC0qw5GNmwTwfMOYV6OI1ySBHKggzAV/UCC2kgbMmhQoKn4fJRy9GFsND2HsB5eqS1t8P906/DF+mtTH32PD42kJ1ylFxHHjMKavZs9QfWY3WIVZ/cquVT1Br7XkWigKPY6ni9i9vu9tY=,iv:Pl4RhyVjDtrdwYYHzx/CJ7obOO+vPseadm/3156BFP4=,tag:yz7LDiEGghQ+RM2zDxYJ1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
