apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: "9.*"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: reflector
      interval: 24h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
