apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: car-health-check-cache-data
  namespace: car-health-check
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
