apiVersion: ENC[AES256_GCM,data:W5A=,iv:KrmUBPiFOwOuu75zJjxBqtklSUE60NsWreoTKm9L7Es=,tag:1gxtCiVyoAINriPgeiDxXw==,type:str]
kind: ENC[AES256_GCM,data:q21nZDcb,iv:U/XBpk3HlgjKqyljfuaPCrxwkLrS9LD22RG4f+yssRA=,tag:iB8eursdCi5MnjI1CXdIUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QzrK/Oji1DUdZTxL/WCjUkRODOzjC3uFStTF,iv:7r2M8T1f3VWTTaCcf3UIAcFtNy88Z8TutjH0Usc32BM=,tag:y8yCHPVZxxFM+dUdmi+gJw==,type:str]
    namespace: ENC[AES256_GCM,data:FYhzQWWrXn92mW1Oaf9SPA==,iv:jIff+y0cM9FslGSyNh6UzrvD022zUbdmYrGMFxlyoGk=,tag:PG4WNPb/mIVHAXfmvSaZrw==,type:str]
data:
    users: ENC[AES256_GCM,data:GcjSL5Qh8UzjHWCYQ4aQfNXj56EmEnetTLS/vj8Sb9NP7qwsKE8uViFXCYMbasRarAzKM0RzXuERpVpD,iv:oQKfRcL5OYvWG2DxW8VmDLiZrP/xKhgFQrVyk6hDzik=,tag:3ESVH4scjnjU3Cfo0DwHRQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:b9hYEGmO2Y8tQHSJ55VOJ1+GNST1d4c1,iv:73DivIN3ESGE8qWApZFjFSBx7LmovoMqSrz0ctBwAHU=,tag:vYWD2MBAl9FIpGnNNKT/wA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNStBNmxiOTU0VzQ1ZGpa
            bXBSZFVQR0t3SGEyaTkvRXpoYkVBREJtMHpzCnRxMTI5YUVwVGl0S092dkwzR2xP
            MElKWFNoYnBnRVIwTkNwMTVVQU9NK0EKLS0tIFc2a201MnYyUTVSdTRJdDI2cWJo
            SXZFR1p1TVZnTmlYMmpRd3ZJR1JzWmcK21CgaNjNKys1BivcHYpVFHpd5/5UUYOl
            2/63+yHVYhHHlRgHNJcpA/jzVPRIGoWGn1tgl4iphq2kUYNJCTjA1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:29:41Z"
    mac: ENC[AES256_GCM,data:ukOJaxUd4h0SEonUAthWmcBsVhHBWKvZwnRhSL5+TPWTkIeZzQLq3NnZ94WVnNWHDummsBj+NaBMMc/GEbU2FB8J8DHFYZ1OznFG840+tG28J5mD/TzkiWLxqCUTPPihQgfbMttqnlRIcpNes14+CZ3kXc/uNaPFwYtJAsVwUEs=,iv:6JQwivGPSuSRbcidiWiQqiXB9GvtE8kIw9dmhJxBQco=,tag:3mONGVWGxtpnyRagZYsBEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
