apiVersion: ENC[AES256_GCM,data:phY=,iv:RdD+inmxyffG5pdp4R/+qgxa1ZPjR4LptbtvVeHNGYo=,tag:8YKbfn3PgsTVVNzXC6PSUA==,type:str]
kind: ENC[AES256_GCM,data:m36uScxX,iv:kcLEPGYjQjO66NpnyKQ+LM2mj0wrRJfTWYaqa67cObo=,tag:GmtFeo6baIdW/3bas7rKqw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TRRveTs90z+vuykjA2zZALOwa+0l3TEl0ZFp,iv:/KAY2TuCZVGAR+TZ+hZ1hfbOzR+pgjMgiYoysKRlHqU=,tag:XObihVsxC6OyzmF3rJETFg==,type:str]
    namespace: ENC[AES256_GCM,data:gwblMLR8KLp9wLjVtPEOcg==,iv:sk+ONyx5CjDvn8KXGgS3Jpb35DJQLFaNDRCuKGy1mRs=,tag:bRzErQ5TBFBF8KgU4sWqrQ==,type:str]
data:
    users: ENC[AES256_GCM,data:fYF/2RU5QYDIo7CdaA8gw04DkRWlYO9QM2/Mhx+cYx5/UydscAAF3iWsV2D3PIjP+XdFMjc8j3vUqIyL,iv:0HKKlNDcfs1Njj0STRmCwYW7vSOOlYds1F4ZjRotjKM=,tag:8H22Ei6RcdolpqZq0lMmxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QUsxcFo5dys5ajBMRXo2
            ZDd1NFhxZXFyRnB6NFRQd0ZnR0pSZ0NHTlJjCjErcEY1dXpaK1dwUUNuSHJxT2d5
            WWhxVVNrWSt6WlhCeWlSUTZGR2ZLRFEKLS0tIHUvRmZCVVZzeVd1Ujc5NmwzMjVY
            REEyUTE4cHM1QWZicis3VnVzek9kU3cKPD0suV/ffZt/cmiw3YBB8I8Wm9H4HhJ1
            W+2RsphjCZTuxOLT/56e/krZIxPC6YLTE53jkd4rCoZMGEVzbcg3jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:40:01Z"
    mac: ENC[AES256_GCM,data:AiMpfwsjjzsf21pyrDEbqze6ZFW125CZkTujc+CrRwup266sWwpx+cun8/6MtIxD/8Y2KrzML/DcKtHovMlFYR+nUUosJvQ07Vxux3lzFCHQUpVvMpRvhn3zwIUrxf0muOWEJ+W3DdOKEZfhoeNLTThMyziRIVThhQ4CaK+CX4M=,iv:5XWw8b/124A3+/fFB/Q2L0olX0tjW8jlMilxfm8+6QY=,tag:2p//DIvWdQhXkrmcf31LZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
