apiVersion: ENC[AES256_GCM,data:RM4=,iv:FZ8G2bVtxs37b0Ycs3pTqBS67BF+zv1LgGJcoU2YDEE=,tag:rcj+91BdsDx6aS+B9NO47w==,type:str]
kind: ENC[AES256_GCM,data:0wth+qkb,iv:V3+kltlRZnmOsxgvfmPKCwJsjezp5SVTMwcYSItL7Rk=,tag:SgaFv83LEBKvpi5OGE1Tow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HN+/mBo8x/KWulMAfrS1pIPA8w1vpXCYuvPr,iv:ke+xvCfaXQ+6cT6zehCxG4dobWT/fYuk/RC+kMAevYA=,tag:WX3ELXu+5GALdxIyjpXdKA==,type:str]
    namespace: ENC[AES256_GCM,data:J2SDYCRpPNGnV2037sBbtQ==,iv:/VJ49xAdM8V+aJvJWf4M5gwuhRdCGhAMKG/PvXJGZEM=,tag:jkLraaB/C8Z0bZTWi0pfLg==,type:str]
data:
    users: ENC[AES256_GCM,data:7laxChq2XSlYnzdn2S58HlKxiNvSNk4dsyORsIzasoKa07Wc84I2EfWqg5znwKh+gJ6kDcoQKnGpdQm4,iv:WtiYkWt8nU0VgAajGoTAeyCqTcseiFnwXljXWCTUS8w=,tag:Uf5zNm8NvftJm5HEGBwpnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUTJIK0lvK1JNaHBlN0Vv
            cVIzQ1ZUbFcxWGpKdjE1OWtLZ0pjSEhVMEc4CkV0RVR5NDdyZ05hWlRlZ29wdGdZ
            MFYvYytjdHJLZmY2T0ZpdzZkVWxTU2MKLS0tIE9FeG5oRmhTdmVNUUJRWTdsbUk3
            dWRDSC9hazNwb0tNRTRGb0tGK1VUMUUK2IABz+PNVGBpLjCWCP11EpQF3+8cHQC5
            8K7mQcstueijCuJfpAZcghXalIl73xnN62wBzO7fAZQ/gZSn3E/2OA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-18T11:06:06Z"
    mac: ENC[AES256_GCM,data:lW7IVB3j/Iko6Gz8UR6GSmAesj/kOh4E+/6yltpGCmD28UZdF4eKEsjBYn2LTJNnkQU+ysntv99B6Dc76uA2M3FCROX3es4HkyKoGQySkRJZ4CsgjTFAite7MzIJpjciTtbB8pHTtKIeHoibwZx0CU7hGKFZvGlH6SzRIlDpb00=,iv:em/UT6SYtuxtDwG1t50qz8GCZXV+WBkKHijZQcs/G7Q=,tag:n9yRqA+0lIe2KqDBEitw3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
