#ENC[AES256_GCM,data:yXWEnMJbMEk7L5K+DHJRDPNcETylCguAvQi16N2B9Fu9gdclxntZsMM4MhajDo1s39pYrO7d+dLF47ZxNXg2yLs+xYKOWoU=,iv:V6V+e99Iv8DUcVdIlE7ytRnZMZ3Pp3KnEHERm0n0K7M=,tag:NJG4nLv6PTJFUUT4DUIumw==,type:comment]
#ENC[AES256_GCM,data:4WuEz+LR+4UhL8+Qsa3ntO/KNHPstqyFCQ/4LA2kHQUkqv0TyaLB0r844qFiFOoINyr526y/BsFLbrohXWbauk7sEaLkMC/S,iv:OssxR2to0qzvCWAOWRYhGdapYbbz0QXcvdXinOl1RuU=,tag:4LdWcn+34Pn9lmClOqq/nQ==,type:comment]
#ENC[AES256_GCM,data:lsZlE2kCnG1uOl2nF7wd3sC5KPLGa/FYH6sgegEoap3n5bUhBaaeic+VTLJq/ex2mHpmxDd2qoYd6FZFjQAyfgqBJWU+HQ==,iv:iXEfXyDYRMLazx2Ho+F5CWKJVwce2L605aABJl9FjGU=,tag:fMEmdiN8kicTj6l6Uc+qjA==,type:comment]
#ENC[AES256_GCM,data:Za4WPKNi7R+CfbxoF21CZiPW77+QfwEkUbFiyRyMuDp9vb4iFRo5WV570jH6MTP9Istk1BGuj19i5BqLqjpGI12pT6pG5s8=,iv:+bXaw3j8jkwVZ5ztdTMGuOuGWvx3g1upBRHBcpN/2wE=,tag:ddPIkg0D08oB2INUIlqq6g==,type:comment]
#ENC[AES256_GCM,data:9omDL0eBuo8NaHcc,iv:kJfXvwisaSuS4tp6J53v0AONy5/hmRphyMkAM/9mNNE=,tag:Sqa3OGwJF47KWFMdYXZwSg==,type:comment]
apiVersion: ENC[AES256_GCM,data:JsA=,iv:ymsG32IjySAMpiKTcNiV5Aye+Wm01uK+qgkIrKXl4No=,tag:BFN5b8VyNeJ+mJ0xvQBleQ==,type:str]
kind: ENC[AES256_GCM,data:qKUoVrTW,iv:nO3xjuUcI83Ale81aZap4aZbrHXgwnh99LxmQHAgKpg=,tag:1wtj2mqmChkRWlqQZWqCNw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:84GVSBbf67f2lW9nUFzAzPPIJXKK4ntyKdluvGLGcZBbkVJ2cw==,iv:wwWQsNFwCgKGqfvhbWyqi8zaD3yfAtfjS5Nt/IZ+XUg=,tag:H+AlOw35QuQ2jvkXEwDH+g==,type:str]
    namespace: ENC[AES256_GCM,data:dnPaHck4tfhyISUQR7Q8pA==,iv:xYgvXIu1o9XTHy3X+4i+CXTXKJlWlaL3XEYkaMtyOLQ=,tag:imftLcSaDsFsBPy7QRkgHg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:BiqXLK2H/lD+VL63dv1RgzzpfGm9SOH3,iv:tLZ9rTnZANCgVJBbw+l3L5Br6p8k5YdGZU7cJcerLDQ=,tag:Fuii0wgx8AAUKl93x+QMag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcXcvVHcxdU9EZ2RYWUJ5
            YnFqWFdkSURqdUpwNHhJM1RKN1R6cU9Jb1VNClhqd2xkYmg0amg3cFRvT0k3bXR2
            RG95VUl3RElRZUZKRGFjUWpkWVBVdVkKLS0tIGEwVXEwVWI2REpwT29kYzU4bmcy
            UmlqZnlFS29RMnE4YmpsT3k5OUc2bjQKdSFBzuJRgIj5M/0aRcDdg3FJgUVI6uBY
            +Zl+mTlW3qixu76Z72rBiW7EsDIumAYr+uiiYjuvPS3aHKK8Rdoigg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:40:01Z"
    mac: ENC[AES256_GCM,data:er/KFbhCxlb95zHVcos/+7ivNm2iOe6/cy9sS1H8zAyWtfuEKrPCQq8zsXMKdzncBiflhrfIwzV9roABnzSrtNwKn9IQHfBnyNONxxAxS46lUWRLBWZVLu8lY0UZ8Lrt84VaY6DHXIVHkuuhoAlFY6z4j456LPrMEkWwD7EzYiE=,iv:Rz2MeZYNiuXI/sYdIOdblAj2R29ItOFO7J8Ai/wmbqg=,tag:1Rm/MeAa2Haveye659g8Uw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
