apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "128MB"

  bootstrap:
    initdb:
      database: tandoor
      owner: tandoor
      secret:
        name: postgres-tandoor-user

  storage:
    size: 10Gi
    storageClass: longhorn

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
