apiVersion: ENC[AES256_GCM,data:xMs=,iv:bxI2bJAlfRcBA2YLdLObBK40h5vS1ww459/zOnxQWWc=,tag:0wpmZF6vWa+SiIJwkcRdQQ==,type:str]
kind: ENC[AES256_GCM,data:as/WNkK+,iv:WvISeUN44mUzSLlZKu5KFMLIKNbsfvlc+1Fw5OClHfo=,tag:Jz/JYsdGW055Qha+EtzHCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QkzynQjZxnAqX9cloAlL3ruZO8mm,iv:6iPsZVCKQUuXzpodUmUtAjuioHvhn6MoInzfph45GSs=,tag:LhWZrElgjbkiVf8jiJpXBQ==,type:str]
    namespace: ENC[AES256_GCM,data:meDcxKzZiIE=,iv:o9iTJGlYIo1Hgy/eklD2Bi2DYjXADOUSbIf1pbVzwa4=,tag:vh5ln2f4TxmSw9MopHHMEA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Q1gTUKmGFg==,iv:2ah4Wh8QTTqvhAswV7DAFQ4h7dYe1ysVSOlxqnB5zog=,tag:XcmFuhtiI1IYoVeDKXBq6A==,type:str]
    password: ENC[AES256_GCM,data:mqu6ITQMdX7dF941m7EvJmg8Bs0SvxWqGEcZTjTIiP8=,iv:xU2PTmLeSUHltJpITOCSQkpQX58ceoBaamJg7WBuIE0=,tag:QIgvJefzEoSqA9xzUoBBig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVWVQR1dkR0loUUhWZ1Fi
            UTA2SDhRZzRuSVBCSUplSXk0Q2Z3eUk2bHl3CkdrOEN2K2N1T2cyYXEyR0Nkem1P
            dUFLOVFqNERDYW1OTjlhRFBJajBPNDAKLS0tIFp4bzZ6WmtIa3Z0c0swUGlDR2JY
            SXI1aWN0UjdobEhHdkMreHZFWUJ3ZE0KUwRZICjwR3Hoz9sKDbd5ATkFEpQEcjfN
            GIEZOFDlrr7q0Vib+0M2t407T9GE1XHPCqEt1nt21+1W7psPl5Qbiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T13:41:23Z"
    mac: ENC[AES256_GCM,data:z3aPDUtYRD/waHj1CMeox4M5wOM5TNk9ESS82ilTJthtOkj73wjXGa6XtjPPgjxeproMutz9MBRTbJH5ovhb7bQhi3Amc5QSW9jcEAyvXncSZcRM1xFSWEYpeadlTljv4/Uimot5R8LWEFuSfExm6mDERnG8oM9VuEBtHxDXGlM=,iv:darMOgIK3wLruQ4rzlkP7/gV590gyJGcj2trmeThFAQ=,tag:pRonp+DYh/+vx4EGtjXrug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
