apiVersion: ENC[AES256_GCM,data:h9w=,iv:wx5LprmvfHAKKU3ysGrp0ZpWhV0PSKab58RvAYqnlxg=,tag:pIlTQFFajo6Tc6X/Dz8Idg==,type:str]
kind: ENC[AES256_GCM,data:yhEp+yjg,iv:RxY3riRic2yssxEdUG44I+PnAgwh9Z9YLKp0dzrTCgI=,tag:kXgyM4MENgmUXO/ik1PwSg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aLbjlpYT9RTP7314qbeOZYNicaSO,iv:JElKkK3r6nV7ptEHB+aOuPwE7cvZUrSAUsMQocKhMW0=,tag:Y9O80wAx2trYGvg1kr/OEA==,type:str]
    namespace: ENC[AES256_GCM,data:ZkbgVVhFbhI=,iv:oJ+8Q+MBM1gjaWXfCltY3C8qmA5/WyGud9/6nh5crHI=,tag:PbV1QXit3O3zR5rH9gdFxA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:WlV012eMHQ==,iv:riDWzgFCe1MsKhnZ0FHinoJt9HmmDsTBTzG9YdbtDvU=,tag:+0bLS7xNWEtvzCAQX8wGlQ==,type:str]
    password: ENC[AES256_GCM,data:1UnVlIp/8q0hkOBnR2+TUl0tjzkYrlDH0UWWlyzxOU4=,iv:NlZLBw8h6OZGZd0xxPNkT28qHv/a7vgkcLWO7Gg/ZtE=,tag:CKR74/JI6fCb6nHt/TrH4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXREszeGZWZEtsZXFMWFZo
            V05IVEJJcVpNL21JOHhORzg3SVhoWm4vMkdFCjVnVmFTYmpEM3hxOTJRSTlLL2Jk
            ZEYvb1JRdmJnci84K1lOUXIyOVlDdTAKLS0tIDNoZWVPL1FIamRtYTlaT3BFNi9V
            OXQ2QzcrYXVLcFVkeWlkaSthdHZXSGsKibCtGSysHcCzpNTGKr2tM3I5kTi1jjk6
            MRRh1aeYpE/9cofUj8MYDhHlHnxOy3b0BQyCxBpL4hSvHYjvfv1D4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-18T14:29:18Z"
    mac: ENC[AES256_GCM,data:isy5dlAGLCQmw3AknWeluQtiBtklhHvK3gszrTWTFSMSOMHhCs3T7EHkf42My2KS5BbFmotIKxZDe4ZJdMYxlUd8hhr3rKsyNX/LaXOgfe17uOLbY0ODCUOPXxVGn4Ay6W12Xv2h2JyD+QyAP9MG8AbDNfBcX22YQxdxGgFxfOQ=,iv:Rl6shehTEKMHx7bfSTNsR28AbL56CaRIAqYuPrR8p8c=,tag:07uHaMpa3z4y7FTnN+EcXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
