apiVersion: ENC[AES256_GCM,data:iww=,iv:gVWYN9Tb062VDKvUI/2yuLRrJYeQBvei/Yz+WP1Gj0A=,tag:Lh+V6BlDd9o1xi7pzfzAZg==,type:str]
kind: ENC[AES256_GCM,data:/RC+t8tm,iv:CxyLUBJ9LnxeVE3yKopqBIie8LumwbwtBHR11SjYltE=,tag:xQ/EkO2bv5SfFQO/+BKAZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:e/LhUPaCAh3odJCY43n0my16stFL,iv:sDyFm3yL4owIu1Kiux7jXA7cnw+n7yJAgKZ64IpMqnM=,tag:XcXK8Dn5U5COn3OgrTEJcA==,type:str]
    namespace: ENC[AES256_GCM,data:898AhRmhuSc=,iv:BQG1KPL2B8iZkkYnDSGwOblzrrV24OEIvq0azUCafHI=,tag:i1gZ0BV3/V2T6sn2XpnTDA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:XrCP7KvlEQ==,iv:3epoCY8L5Q8TODE2GA7oBAxKwbsLRSdCiIyWIwQB3vU=,tag:zTzjA9nyx8sVMCEaIFYufg==,type:str]
    password: ENC[AES256_GCM,data:4JjLasBoNQOG5UPA955U8RBw7tfZ4Pjh+W4cFgVB9Nw=,iv:Tk4nUjaJIKRbLREwACaSB7mjGfWWCZFsmyTetkEZFWY=,tag:EAeijNrimv+o//ZyjkJwDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUzdkWDFRcEd5R0w4VEdV
            cUdnU0lENFd4OUZZVmdxOE44WjkyNXhDVW44CjdVQ2FoellsR0Y0UE90bFJXVzZr
            UEwxT25iQzIxTFhDY1dyMXRqbFI3TW8KLS0tIEp2YWcwSWNuRmJobm9SYXpnNU1l
            dlROdEFTS0RoVnl5ZHhSOXhzcUpLcHcKXrwBkxUFnrtF07GXSb2/84J5P7TsY4Pz
            oJmI7+6maG/zs7xgP2HOmHV21pyJZ//WK1oOQF32pVvk3ww/fU87FQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-16T07:57:28Z"
    mac: ENC[AES256_GCM,data:q37bCXy5aHmThceP/VIhNIm17C8O6jvCvXb6Dir0klcRqvjLUZfVnxYX16fFcf2614Wo316XZpDF/WMX9lB5NLQBIofHu1sHZTe6mrolg+bkMm8lyEmLOusD6MwC7rtGp1RSHB3z7Wm2AavL0VTKyiDVQCPzwbVG0u7PFB9GC5Q=,iv:lZ5XVLE4iyPQUJyGFGFtqPiAt8P2o1n1NsymB82/KdA=,tag:5AY8WxcTQP9ANs3rFDDDpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
