apiVersion: ENC[AES256_GCM,data:Wrs=,iv:MkUa6qzrlJcZEKSXcgEKa/RqS1W551kT1MuETvgqPxg=,tag:tMs6UNNXrAyvXFw1fCFHWA==,type:str]
kind: ENC[AES256_GCM,data:TbsV7us4,iv:tTbUaOk2c54G+gCNfuJkaXO0GlYkbw0iYjEwHF+09aM=,tag:NLhoKOxmwyGf8YiXG06wyg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jaCXxz0LHZNB1Fs5E35jungq,iv:8q70jbB0jkWWx8IrkqPH/QVp5GElGr9W6dt3fdm5EPA=,tag:u7qfUSQ14w4nWtX+X3T9GA==,type:str]
    namespace: ENC[AES256_GCM,data:WhlSMeDiWg==,iv:tQ1c9TaT7RQ0EyP4Aq1lae7Y6k9/QSKeo9qhyQ1+Or0=,tag:J/mmevZWTNfLG7DYjzPMFQ==,type:str]
stringData:
    users: ENC[AES256_GCM,data:p7Ipi3ZWJmiI8zMlZyZx4aQVO5YhcfbGM2uS8+1gKkgsqx/ClHEC+huSDihW1B0Y/MRmAFLLi+7U9nmjUF5J3AILAjWT,iv:CZyOFZUmEyyAwQh9yn98mM3RmFA1UupVlNPoMVMp7bM=,tag:VhPAHmrt0SkV+jJzBiE8Sw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWGV0REtLQWRXQW5idFhV
            TmRwSjRWRUlmQUY5TVhMaGNJK0lZaWRLazI4CkVhb3hBWHgwQTYzSDYzRVhwTVVp
            bnc1RFNGMWtpemhPbFVFaVNrYzVCclkKLS0tIGJWcC9OSXdWaTM2K3NwbGlhQXU1
            TzBDaFZ3ekp3cE1rRGdYT3U0U3pMaGMKQxjl1x5HSz3IkIDiUMKX5FeJXjyOWedc
            KDvniIZVD9d6IrI2fxHt2nmwvCTeT9tEDrBPivH9QNovXBSQa/7wrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-21T17:52:04Z"
    mac: ENC[AES256_GCM,data:6txCCQuqDZ4qheCXaylJ3Yb9UTeDbUKBS1K+cmHQQtuqCZclORMNDqwFaZvnwlqTf8jQMkY4Qj4nWuIUpj0pUSubNAab6YlNvSDJGf0b0HCdlbdVvskQGCbtM4Ui7wy0KX/nKDfaUmt0dKozXo/GcMD95L8nfKgHbJJu+9jlTiI=,iv:4SJEcvTxW4VaMKYg4wnVoJG4yfz8HLqiv0sJTtNzC8k=,tag:aWeenGVnZx2dDBJYMe+aDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
