apiVersion: ENC[AES256_GCM,data:MMc=,iv:dIcfwUdRkk9sHNchKVVfZAAl26rOhlar1vVzYLT7cNk=,tag:S+JVMknawgP2ulmLW9atVA==,type:str]
kind: ENC[AES256_GCM,data:y0xmU/Mk,iv:nnmevMlXFWlH/Rc+0PIi8tfDOEbwJlB/roaMCsm3yto=,tag:eETw0ejLLEn8c+xfYFzvDA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:roU8NAE8DGdhVUsaWPJKTpzabxPhduWsRJ6I2A==,iv:pNm3u9w6w4CuUt3F+oHpKbr1nhp2HCTsWXBhWXVLZiU=,tag:xnnVQHTHuFD3+ImtM9Fbfw==,type:str]
    namespace: ENC[AES256_GCM,data:BNkLU0Gwkw==,iv:qwTlZXbwVMgjg+ZA75pAkvmIA1jwAlG1oDDyrDXYKfg=,tag:2VIDosHkkenDgpMN6mSZxQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:rD3ziLWjzOKqJM2ynjOJF6QHj4RoY5Twl4XK7cxZ4FU=,iv:R1mu8/FVCZQbgSgwBwKXjpU9OnibG4QAqi37TAOVBoI=,tag:9ggFXjQPUoD36W0SFFt72g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjlyTDVsREEwQ1dnK093
            eGc2MVNCakkxZVdmT3ZCQWQ2UGkzYjZiK1FVCklDR256UE5DQU1MWVdtM0NlTERo
            UHFNU0F4ZVZzRmZjUTlBMk9hMWs5VjgKLS0tIGVqMitsMkNxUTQxMGhyTWxLTVkv
            TmtiNjJ2OE5EZk56MERld0RDem5HR28K+04JePEwjPF58oGtnrKuEiTq17yZJzE3
            aGXLc1BzAHEGBYPjPbjVr4wplbkmdX/HALlefEyAgNxlRz8toFct4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-21T17:52:04Z"
    mac: ENC[AES256_GCM,data:aa5h+8wNk6yzq9wFL83Dbaq42zTHFYQ56R75W0Ss5mbDcy1dR1LlzLFbym/AHiTycfFBsUBeKoWnI22sR9ulXc1nBBX5cDIZKhSaVlUPqnxeuUw9w7wc+ls7LB/T13nEVmSnK9LEEAup8zk/fiO6pxy/Zv5T84zJaW9nSHYiChM=,iv:0J2/nsj+ys5aIOHwX+Am1yIM7NpSzr61AY6Z4MkLtww=,tag:K/ATObMByreqn05Bd67xTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
