apiVersion: apps/v1
kind: Deployment
metadata:
  name: trek
  namespace: trek
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: trek
  template:
    metadata:
      labels:
        app: trek
    spec:
      containers:
        - name: trek
          image: mauriceboe/trek:latest
          envFrom:
            - configMapRef:
                name: trek-config
            - secretRef:
                name: trek-secret
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: uploads
              mountPath: /app/uploads
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: trek-data
        - name: uploads
          persistentVolumeClaim:
            claimName: trek-uploads
