apiVersion: ENC[AES256_GCM,data:aik=,iv:34Vx07eAP4BK089bXwh4xZwo9nHCyVhQgJXnzINPo00=,tag:MXpQVW2WcxZ4EIuuor1ccg==,type:str]
kind: ENC[AES256_GCM,data:yO4zDL+E,iv:clucwlFRTQHPK0/9JfeSsb4jbdgV8Z+WrviqIHuS9zQ=,tag:Lke2CdkQ6lbF2MBs2znTCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:axnBXid3X1UV2rk=,iv:pbvCqsHADDVIOGNtvhyjQ87CENvr/yromhlfWW8oyRk=,tag:WIPjICV1u2h8x/jU67uffQ==,type:str]
    namespace: ENC[AES256_GCM,data:qZjs3A==,iv:C6HxsDL8gqmehw8utnDBApZwJqqaxy7EvTmHR+bVIcI=,tag:iHOZ4C16ZhL+MILOVj/a+w==,type:str]
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:sIvWHFXQwhPtpI2BJEc4eNTgImYabrgfezaStShnp/ur4NLsdifL9Ib37ukkFjMssOpuaMq2/ih+HbRCHXiY/g==,iv:dXGF36sUtusezLRJ+47wMlM/RstXrN93INe3+BTaoO0=,tag:K6Jd/wuj7dw+saRLHJd7CA==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:AqpWk6Zn95MHiJ1DdNn4dQWkvZ14RA==,iv:bIF+5IHxwq9Clq3xs2fPxTNNigNmmAglsdLsm0G8fO0=,tag:OC/jH4npHSwslT3rfAsMuA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:HFfc3tUFTZybb/rc611ym1sPcuFW1mij,iv:bwmeNoH4jCQmcSH3U025TcmuhOzszCiCM9RmIFvXZLc=,tag:RiXbv4oqEU5ERIw/ek1T5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdmR0U25VZEsrckFMVkpR
            WmVIaS9uK2JMNTg5TnJyMk1nZE9zUW94dGx3CmhQOFZRYmpaNzJ4VmJyVDUyUkdY
            SjN1RVYwSWd3YllOTEVXemZEVkpHUXcKLS0tIGpGaVdlVlM3ejJwN2tJdUFmUEda
            STU3Z1hTb0hkMCswa3N0RlBxT3VXL0EKqEnrWTq3znnHa03N+nafcCdLoZ4v8gYX
            hsZWEmPOEslG1NITsw/7TxHE4P8NAak08EUBRqNqYXfKoXHIKybzRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-07-03T13:22:56Z"
    mac: ENC[AES256_GCM,data:+PnVCK5c/ohaBIu3Woa1EJBAUUcb5CFliu2hNNeoWDHorCceD9gwP48LqjHIZbTJgsC+McSygBmHlxV6PE6Sh3nTmWcblFY7YdwA0WMtdwJgliIyZXoXR+fhbG804Bm7uyvuIKIB8/In6K8Fyrho0tbdRMwx5m5jly9ewLWjGB8=,iv:yUhA1vUqS/OoIY3ujOOV4jhQ0e5lzXC8TuY3HbeLJOU=,tag:pwswqFWtcX30HRYXImZsGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
