apiVersion: ENC[AES256_GCM,data:X8Y=,iv:g7MOkAKfAIpS+SurqH9QZxlNUvae8snY9gPhZvVaWEk=,tag:fENaKnyf0z7voVgJRZ4Kjw==,type:str]
kind: ENC[AES256_GCM,data:AiVgNybv,iv:W/5U5Br7ExpMst6zFiUAxUZSx2IeKar10TddoM0Rg8U=,tag:Dyaptlm6Nz30nbnk46xXTg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:F/BcA548zR48bLI=,iv:y9CZlKkPVEx23t0QmRjWj+xD1X4grYwG2u6wZOBWuOY=,tag:1BYexzCeDnCmbZG1am9s4w==,type:str]
    namespace: ENC[AES256_GCM,data:U0TdPg==,iv:fdB7Ec45l47cSAGT0wtwfY5wIdUc7TGIUQTmwQUZCdk=,tag:r4mjLnf+tV18vVEo7yGOnA==,type:str]
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:cmoI1o6ySnOA8/iAQs13uhcxrIhNLGtgWupYSYV1RlnZcCSmCohNsc1UnR1yNvdjCQeGay6WEeFACzlJ9l5rcQ==,iv:dJN2wCMctu2G3gRHNWUWUA0uo/L66jn9x4D6JPymeuU=,tag:pDkL+Q+UndmAirN1omBdkg==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:ivQOKAik1dHgfJll9oH4kSfd+og5rDg=,iv:Id/t7sgHzBpmKiEnZEntoFjQX06f+aM+NfMSVzxMyHg=,tag:CYYXqS5p5oZSlmT1gltO6w==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:SCr2DTRmx545v3bTcUZeSm/wnw/no9TT,iv:VQlylsZSX3WZFjnPzZ1/w3vsG/DsmP5ma4kNomjG3OY=,tag:LFyfi8e/qYFphlciYVYXhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDajRuZFdSdTZCZDhTaVhP
            RkdVV3V3K0hkNFdVc3JHMVRnNW50U0RZSGh3Cmk0dUdxZGJnNzFBcGEwM2lvNWpu
            SzNBdi8yOGQvcktMOHhTS1QySTFyRGcKLS0tIHk0K3FvZXVibndjeEp6b1pBQ1g5
            aGpCU3JjVm93K21HODNIWmNValJnQ28KQWIixmPPLyMUhi2JL6OA0lbObH6nEbes
            NGhps8sz2QCn3D2tEMZcXaLmdcQW6hWwxpYLHJNlH5aGEJcLIzj3SA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-07-03T13:55:13Z"
    mac: ENC[AES256_GCM,data:MfLgyd+eOHEVw1FI1YGIUkF92tjbs62hrjycGYutSbhgPHLmeSKFCVGdZarvQ+tF4YXK7K4hOt6GoYD0UvUuOxpSTwe0aUj7FkBRoBKZT7teYHopnzWhE0buplPx+5envBnd4GmzTNq35Hw/NtXFRRR+1S11HyKUy8tRFijeFWQ=,iv:FsVj+X9RjJC1AAVyBq0g//Dfy5MbYqNLt3paAkl832g=,tag:BvTRU4WuqOXOsYXEq42T1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
