apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-cluster-superuser
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postgres-cluster-superuser
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/postgres/admin
        property: username
    - secretKey: password
      remoteRef:
        key: secret/postgres/admin
        property: password
