apiService:
  image: berkeleyskypilot/skypilot:0.12.0

  # Nodes have 4 CPU / 8GB each — bypass the 4CPU/8GB single-pod requirement
  skipResourceCheck: true

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

ingress-nginx:
  controller:
    service:
      annotations:
        lbipam.cilium.io/ips: "192.168.0.8"

  persistence:
    enabled: true
    storageClass: longhorn
    size: 5Gi

  env:
    - name: SKYPILOT_DISABLE_USAGE_COLLECTION
      value: "1"
