apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "32.1.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 24h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    deployment:
      replicas: 1

    service:
      type: LoadBalancer
      annotations:
        lbipam.cilium.io/ips: "192.168.0.2"

    ports:
      web:
        port: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
      websecure:
        port: 443
        tls:
          enabled: true

    ingressClass:
      enabled: true
      isDefaultClass: true

    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true

    logs:
      general:
        level: INFO

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
