apiVersion: v1
kind: Service
metadata:
  name: github-homeops-broker
  namespace: github-homeops-broker
spec:
  selector:
    app: github-homeops-broker
  ports:
    - name: http
      port: 80
      targetPort: 8080
