defaultSettings:
  # Replicate data across 2 of 3 nodes — survives one node failure
  defaultReplicaCount: 2

persistence:
  # Make Longhorn the default StorageClass
  defaultClass: true
  defaultClassReplicaCount: 2

service:
  ui:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: "192.168.0.4"
