apiVersion: ENC[AES256_GCM,data:Npo=,iv:2BBb//XunZOpi0mwmpxM8v/vUryIU9baxiFWf7fr/mc=,tag:sqMSLfAO0DQmsvqJJ0CN+g==,type:str]
kind: ENC[AES256_GCM,data:gTuQnZoO,iv:SvNUXdokEIfpiEWxgDtqNxncKJbeJcTlVq/mesRHS4c=,tag:KIrd0FaaTQ0HEeh3UtnrDA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Hk0DB9UlGHYSViHTBZEiJ742Db6UjhrhksXg,iv:sVL2Onz9coI0UmsFl2kcgJ45ALfr/AoKTTHHyoQOAVw=,tag:b6Lnk2hvs4MX/4pwqrmR5Q==,type:str]
    namespace: ENC[AES256_GCM,data:b+wsJaCSrbtH530=,iv:BfRtJ39jHnsvMI9yGY5+WjWS8PQLjZv0usF8aftPqGo=,tag:9iNbWhPLSd5Nzcdst95xUQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:l2NzRwdUuw==,iv:h13kjdwa9LiNTM38B2bPIZ8pbBEAD4r8cMPNdprCA90=,tag:OgFG9udrA8h/rOUHhNiT5A==,type:str]
    password: ENC[AES256_GCM,data:Wlz+0j0CxbWC+PGZhGZoV6K8dOxChjnB,iv:KGff9hKj/v68Z4h4AsCVXBFPW09oqHjvHPOqeZ+Xq5c=,tag:C3jtSBOo1TuhvG/26EUWDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTVJqZzFBMG56QitnQzFn
            a2VwMHEwNkdlajFTYklvc1ZGbEozQzZ6c21nCmVFUE1CUE1JeC9ZQ1Q1TVYzSVFJ
            ME1WeGRmMnhSdjdOUXdiSzlOdnpwVXcKLS0tIC9HMWNqVm81ejB1K01NZi9BVWVB
            cUt3UERwalFnMW1oS1lpZnhqVWlNUDAKxUFILkPTJrHcu2l0dH4x5Bn8XKjkMwaY
            2rh/bDBW2diRsWY43UxoIgkgkokU47i+z9BILhJPpRmwY5B7sQNpVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-24T14:32:55Z"
    mac: ENC[AES256_GCM,data:USH/9dn4gJhLJmOJaLqAItu+Wg7aYUbqB0Zv7yuujdIUiatVP/eqewdhjh37gqqUVfCpTRL69/LIT/Ofpkj4prjyYnYTYs0WioklbFgoJSEjwSm1fBY/g1ysGxgT6/Ct9+j5Ron1U6vuq2El780foH8Ui0NwRTosm4O5CyEostU=,iv:x3zYp3JLuw2qrdYL0daUxYO2/I78UT/VWPCwpZMWDwU=,tag:X09xabYMgCREAaS8WN4hNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
