apiVersion: ENC[AES256_GCM,data:SMI=,iv:q3WNOE6tPOxFtlEYbSD/ndiljeC66m5Pj4jqc+bc+x8=,tag:i/mBe046OTepIJjs0H884Q==,type:str]
kind: ENC[AES256_GCM,data:gsDtQxUU,iv:+TErx63xravd07APdhnZZ9oP44HZBmcvlLPsedAQq9g=,tag:IDfh12YqeWlx1Zl7pDGDtw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S7LFKRJMbMMv2x44eIbankcE4mdZ,iv:peb0Lvbg0cbRWDgwJKdbIsfJXr3PH/WpOb4PVNfMx0g=,tag:RCMwdCOP2ciKq055IRCzyg==,type:str]
    namespace: ENC[AES256_GCM,data:wUMEzPCNwV4=,iv:qJ0/XlcGXrVYmuVaEjpTbviGRSbeC4F9xZGwuvgIaco=,tag:rww6idL2PIXEmwBS4dzyLA==,type:str]
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:trgD649tsaXxBXexr5AhAAKe6xvCFieOgtZluLMjQ4my3af3vy4Kdg==,iv:OcHGwsf3RRvwKCk96DXXs1PyvDV8ozPu5IziiFi5rRw=,tag:eaha706PrMFByAQumBg44A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOVRndFVxL1g0WlliL051
            eEUzMEl3amxGUHRobnFZeVAwanBsM0R5YUJVCnVMVkZKMkN6bG12MkR2a2N5bE9I
            TVoyWWNkeUpDN3pFZm5pald6cXQxenMKLS0tIEFCNHcwcDhqSlJmcmFxUjg5TlFj
            dy85U0dDM2JocTB4bFhDOE1jU0VGYzQKBpYd1PLxMFiW9972P9+X7bNG27G+cFNY
            YqVumxqI8qLt5Lus0CjWKCUEhhyxpShwnfhAVFuFWRbZlRVc1jzeHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T13:41:23Z"
    mac: ENC[AES256_GCM,data:eVpQhE0TYHGzujAXK63Vte3/fW+wyBzu+bg1dprYPbo14MedV5KrWxfAjp1un/9Ff/0rRliOQb/r0jW2PQBZ42+7p79RsGh9IKUEuenY4Oz1q8zUOvWQSbNdulzvS0uPEtExDke8I4INg0MLUWYi3ByVKs/kS8FPDg6ysF3qK0E=,iv:dS8nkx4QCKoXiUZ2VJTTLwkH266RU0pMCuoiYpfXFMc=,tag:lpt9el+oAktQYmG+1c8scQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
