apiVersion: ENC[AES256_GCM,data:QJg=,iv:IDEzrO286vwLaj0OmqVKoDWqXIHXaKZRbn0r8do/2AM=,tag:n3fZoH6dXdFkG7OozerhEg==,type:str]
kind: ENC[AES256_GCM,data:AfC/9HLU,iv:R/W7j2KrCAcM8bI560k7PhaImFiiIaCyOcG+6FS1Ues=,tag:pphTG9gwqDQedVC4vgMO4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9js+kSyd4QPikCegdtzuGMVVJy63,iv:lc6QSxsIkUFd9nn0+Ayaoe/EAN83mJzJECP8LIW51/0=,tag:bZka19pcuYmEqRF/mIf2MQ==,type:str]
    namespace: ENC[AES256_GCM,data:Xf7x+7xDbRM=,iv:FvRPmyFgMEDR7W67BzQkQH8IRx2XsAcVtTDY7Na3+w8=,tag:H6XTWL2GA7oMkamr7e7wHg==,type:str]
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:w7BU1eAEB1l8JswOrmHYk5YqmQ51OHr3hLUhaZKvT4dk7+/KoKe+kw==,iv:/zGmeVqLxKPQsx6f/6S4sn4iLtcsD6oKqIuLwvfTuu0=,tag:BAZaV5Xx/i31IacWw8xh+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYmE0TlF4bmVJR2hSR1FY
            c000L2h3OHB2cFNwMEdHVVdXUVhOeERER1RNCjV2WmN3N2JNS1YrMENDWDgwbGtD
            MmZ0V3BUdjA1aURMdHhrSVlBWmNsOXMKLS0tIGh4NDJXdjEvSHZUaVBxSmxpTVM3
            cDFmaDZLZWRnTUoyL3I0RVFOL0I5ZTAKoH+H790nOofTXnfBLm/Td4qoF+k2swlE
            ak+XExz2e8Uh9ry2ivqONxd/GZazS2y8oKxyUeJlo8vnfB7vpUIyFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-16T07:57:28Z"
    mac: ENC[AES256_GCM,data:YSA7xe2eJyko3GAMjJuJWj+Jj//PrnKjvUHzMXXrY2Bodr4Y9+3HxzEjn627w79BMGT/DM1RMgGVrnOHAWH/ZaLb1//dCYJZVRHVc+0johOTMTcFdipjRIZDPHAX3ukOtzFOxiT5u+9nfMXtli6Sq+3+TlGdrQ+2BxI3HjmQOtk=,iv:RIaIYkuFl13WlLlMSBZRT9b+mexT/bgMgcvEacAeLRs=,tag:zWlq+2xJGEYRilyAlrBVsg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
