apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homepage
  - tandoor
  - blog
  - trek
  - better-booking-bot
  - car-health-check
  - ntfy
  - it-tools
  - mailpit
  - hermes-agent
