apiVersion: ENC[AES256_GCM,data:mwY=,iv:X9kPMVBWdlyCXcMioplTk44WPDaLqozjCffarnMlu+8=,tag:fLl4vH8h0zWPg0MELESyXg==,type:str]
kind: ENC[AES256_GCM,data:zccmKU4r,iv:NUzrrkguK0mAFhQdt1Jut22Ng05SB558ZglEZbGcXeI=,tag:+/CayWm7HJnYXVA+feV/Hw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:86U6mIH1n6c3hNtbmSvU0n57N2M=,iv:qQABHooCWOL7+f3fIN/mE2dKaCCAN/rRFqaVUwhQ7vI=,tag:P5SMjxaWs/12O/lc/iSZZg==,type:str]
    namespace: ENC[AES256_GCM,data:/1QFjQK6OJXKqRo6,iv:8ypImcxv9A6SOoIM9OM8jzPyUH3/z1pB5m4SzAzzIYY=,tag:u0orUUJ8pDHwQfW+mSbAjA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:TijwQh1P90X2zejsdC6KnrzVPWt7/s35tf3NGq+QEoyumcaPMKBYhob835Zcsih9mWmf8VI=,iv:1I5GqW2gWeCajjdMFbj3FNE+lP6Ub33w6NGSbdx8LDg=,tag:ZdSnwYKyYn2rWsY6lWiqww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOFYxS1dodW0rYzVCSWJM
            NW8zbFBlQy9DMDlhV3FUcHBrT1JyZGhkUWpBCnJqaEZPT2pScTVGMWtxY2s3Zkpw
            cW56L200OFpCeE9JSEVKL1hMM0t4MjAKLS0tIEtTTWZ0aTMwK0hkdnVmTThBbERF
            S004QVZhejdVcGlDVzJZYUdkaFF6Nk0Kfr7nhBHYwTCmeUxLSxflIF8WyF0nbO9r
            DJ7MLmojcbXLNvmbYrOu/8D3le8IaGbFfOIZ5pe9V6NidbBbzsGLeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-16T07:57:28Z"
    mac: ENC[AES256_GCM,data:rB5+8or4UxhVDpLdVKHnM+hPbqr7Vlg9fAE2VS3Z6Az42+siBFjiXpMtNtUaYplbkaImowRI7N9SmcHbVrTPbj2Smf4ADqhnKZfkSR1/X2bajJ0JCsV2PWS9dxPY0kWZRME7fLTVOY60+1SIvo+XVueN5JlaKKE5tsvjIYJpwVg=,iv:GhOk79TCFRcK1z7gdW5Xi6eyN5vuPmp8eNgaV2bqyD0=,tag:XONWRTCUR53ook8qWfNGGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
