apiVersion: ENC[AES256_GCM,data:cs8=,iv:n1ml8j+xzGwjTHlg4xNFmeFoz5LW7cJ/hN8rOq6RkXk=,tag:htw/AOBFmbKiM5qdN9S89g==,type:str]
kind: ENC[AES256_GCM,data:YDp2EViG,iv:HpQaV7lZy525oNN00ZiOGvNurO9i79M+UgCLmVBcOeU=,tag:hIkopnzb0/E/U5qf9+fHnQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BeyGxpLSeo7yffSxG2z8lHFx1c4=,iv:DHPmjeAO2u1gMvLlLSz4rec51KOXCIcRbjRkLZKLFEo=,tag:Cq9rtI/7sjZVpoFK82jm5g==,type:str]
    namespace: ENC[AES256_GCM,data:by+DTjNousiHTdYQ,iv:JjHTaACpJC0A4ABND27HbsthKFlQJw1lrvPTaDVIh1g=,tag:39t7Tx1MZ1NXcgE+TzGugw==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:yKtM+goTt98KyqBEDnuMK1dtkTMKAKu9/pBJtUe6TtQXJRBvnYuHOKwOEM6kOFxDtZv7uAM=,iv:L1vBjduUj5P1SjckjSNwiud1TPjRaUzKHVxqDZddyOE=,tag:ZjQqGcg90X181sg+p82GNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL2hvYWdReWQxOFhRZWNs
            SVJzUnI4ZFk4bWZUQm40VE01UVd1bXFRc2owCk02SUpXOHBXTGFzOUkrSEF3N3h1
            ZkRWZjFBWWwvS0NFNzc1QlNBZTVycmMKLS0tIFRNYXJmaHpoZzU5SEdZQjUzVS9j
            YlhyZVgzaEJETUsyb2E5bzZpRjlFYkUKdc4NKC8lH2x87xk9GoxAiOXa5mT20Vzh
            fzSahxNw7IC3pnBlLtSYd0+22j/i/x830NNyXqQ2hSXNCgd5pB5lDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-18T14:29:18Z"
    mac: ENC[AES256_GCM,data:KIfWTdw+LYEv23s49SIY+/9FpzmzZrCwJCOHJJAGuivjDVTmP+2guhaVLMp0NdE6DClWdlMPl8db0bCG+QKo3TlebaGXcAy687ST8K8Mvmm5l6lVKcheQugLm3ATiolv9GXK49ZDNjSdLbsjS+yyc7A11c9cEa5Ejp5P7nNNCqM=,iv:ZFn+DZOcoBkACxeAEPiew4BUkvmZr26GOMjy8RuGPy4=,tag:X52vmLqmKci2/xSS8vckmQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
