apiVersion: ENC[AES256_GCM,data:soM=,iv:N1IsfQMRrHhINgZ7ZKRcWiHea3eQ8/cJYLZeVDceq1M=,tag:1TTToMjrpKmH7x9/vYvpnw==,type:str]
kind: ENC[AES256_GCM,data:O9153R+B,iv:u4TfwJFafFxeZSwXeWe6HAg70TKkmekcHaVOSef62eQ=,tag:qA7ILM1Uhh9iCfH00B4/pg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w9+9PCECvF7/muK6Ja+9opY4byU=,iv:gGnO7ivKlIPERDhoBXvfFYDMWYDoM84ZRaCb0MO2nwA=,tag:DNrbOa+VXDVvYYZMhQ4pxg==,type:str]
    namespace: ENC[AES256_GCM,data:spblXPFKuwn2+fKa,iv:o+cXjbZfYVlytrlInWw5Ae8jzPb8Mgig2vBhvhaec8w=,tag:7D/YFFHfkp+iMhI0k/OVsg==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:gX6A55YWtLqZM2hUKI7vbxeFrd+ekxwb5pa/81ptWmPSl7b42vWIstpA/of+puD5wgs/64E=,iv:ffjxX8X+/xKy1oklIh5MCIsWueObwdTpeqUnzJewvy4=,tag:/J7fWco9d5hU49XCj3J2SQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UWtqMVNGWlNSREtEb1FY
            aUNTWm1VTEV1cnR4SnhxQkREaEdpN2RWcjFzCitsclNGWElWUTZwSWw1ZTA1cCts
            aGgwU2ZaUmdUVHFCVGRWdkc2SVMwRUUKLS0tIEJOVHBVSFBVQ1VRY3JIQ0lEKzYv
            N0JObUE2ZXNqNmQ4djJ1OWMvVmJoM28KUKd5JtlnYmuu6DLPXNp2q1yp3BXKENYW
            Gvf5OlesT5kaABsMjJEq2r3fASesul7ZdthWG7Gq+dlo3HGGK9WKqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T13:41:23Z"
    mac: ENC[AES256_GCM,data:WbAIETzxIjb9gJ0/usbQ96Oq1XuybrrRbajmtiTSL6cN5LYYlbCLOnNpL1YSlm5vIAD2a239ptDHH3cXhMaBmtvx/qGt/yt3GwfN0NDo8uzPUPrOX0fEVHQfQEtL1ro6gM+ig9hut/PNZrqEz8q+XKGFwW3PP6Oq2RmoIcTxg+I=,iv:iirYmTiW54bLBPuXupnne7ceMvJUVzEsg7I7E4M+cVU=,tag:zBXpn9MZMP+155hd3VAyEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
