apiVersion: ENC[AES256_GCM,data:Cx0=,iv:99a0c0+Ara/X5mCptFj8lOyys9bAw5FsHS+tmBJ/z1k=,tag:Yi7WW7v4MD7eDa4lKrsanQ==,type:str]
kind: ENC[AES256_GCM,data:BvBowhXk,iv:zeXU4uWmpTdIlEednfeuiBy3OPn6wogJZrpzEOlsNEk=,tag:GiFzy/7rftdKYjBmuxarIQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/82FW1b8Dz1RzzOcFj7DdNKw,iv:ze66RKvPIcWipltU291ONwW+UEhQJ0LjIjvg+DtaPx0=,tag:rc+qUe0PREHS77YO/NuySA==,type:str]
    namespace: ENC[AES256_GCM,data:aH+njbSAc0Q=,iv:Coe+wxyVeZWRx+ga5L/gIONNNdZiIrxHdeGGSav97Ns=,tag:jc21/LMUrfc+5rY1EcchCQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:qUcvIO6Xrcc=,iv:I838Y4vyHO8tygF7vMINYKEkdvcdefZ7cp7SeLoIwNg=,tag:5i0yVHiu2nz5ODrKSg6Bag==,type:str]
    password: ENC[AES256_GCM,data:EFshwUH4gsX1sGtFw5Ts0RTlO0RdiabLS5GhBPQ2EFw=,iv:mHLyBEJczO+yisjMNBxnV684WvkWcdb7n4jeGztiux8=,tag:Ekct2tGFyDy3Jj4YsWwfiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRXdzL0ZTLzZKek91OEp3
            QzBNWUQxbTRNcnNZRVBGdGZvakd3TmVwR1ZjClkwR0lzRnUyNU1YR0hXRDd2WGtn
            UCtkWHJ2NkloRVhNNzFycW4yME1wRkEKLS0tIG0rS0dRWnA4VzlpUjZXZmE0aEVR
            RXl3SVR2VlVmVEpJWEpOeXFrZTRqeWcKKQXwRBY4aVP/msKD4G1BwrA6clvq894n
            URtXoZ6DNjj+zZ3KRpIiEmjWkpn30LgQ7WV8fPyMZOkkRvC5gbQPUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l2j0cqvl7qv9ahx2levhr9r74sdn2ppf9fxsjhd9ey0wtrqcusaqjug4n2
    lastmodified: "2026-05-13T19:42:54Z"
    mac: ENC[AES256_GCM,data:W/ks0UNhPiRSw7Kn5eYZP4qf9Gh7YEjPillGQH5oNSeu3NDp1CGGF5NBrwqRSr6/t0IaVhcVzJd2y9itVtSOUE7K07vcIfO/Je6R6KdwBUVylOUycDMU5P4gpchnUKssNhgEEKwu6DIZ1Fm+eji29stfF2T3bO36nkVHF/tCIG0=,iv:ULAm4pkxaaaJsYnLjLcvC08ABQ7ynRpdAnTJMQVF7zA=,tag:qEjP5/mCM2qlUfNBjlbkKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
