#ENC[AES256_GCM,data:ofxPagJeqHJOSLreEXxzjiGeHcR1DC0JgvlDfoaa/L1uedM8QRzi2tj0Nh+g6nLa4ZTNvvDdBJjdg7+24eZXB2RqKaB+noU6MLJihQ==,iv:xIP2egrAYSFyJS/5HzRVEu0S1ZPMfm8abbQf3YDCXaI=,tag:mh5TFFffSxWytux/RjEo0g==,type:comment]
#ENC[AES256_GCM,data:w6lE9/LDmJWVsFBy0CINOvYVv3onImTmR4QGj3VdQV+I7U4T94znpzGTrMVhelqMgGoA9BysVQe3Wjr4pX1fGcXri0cOVuKnnhg=,iv:7PQr8ui4DwNM22neFHvgVyZ7QGzfdqSp0Rh9Jl8VAM8=,tag:pNdelYUX/96+cHfeZvbVyw==,type:comment]
#ENC[AES256_GCM,data:147fePvHXukusZWSP9ENWfxQsO9v3i9djzO0QPHH78pa2GNT0LUF1nAsZ8d+QmGJXno80VT15ILneYdBPZSmGp7vKHRRXtN+KA==,iv:1Z4Fhr2bpT195iQ0iDyqrHR5uKiw5KGbCWkQjVOXbIg=,tag:ptvKExxDMgHIrTP1pmntRg==,type:comment]
#ENC[AES256_GCM,data:O6RZTqmd0ErYel+mgPrxSZcTRafOH47cfwbWKsmHyDopf0spq8ke61py/ASxPUhGYqPXC/vkMYhRhLE86eQI2wuMRYyp+KIm4g==,iv:4S0HXX9Tk0uB2ZeEb8pYrw+6ot3BUxLHHd6lLriMsUo=,tag:/Z/x86AR8uNhaOxQXagF6g==,type:comment]
apiVersion: ENC[AES256_GCM,data:79s=,iv:4tJmthxzbTINN5oG/D6hwF02OdPh1WmNTbwoTE7yuE0=,tag:54uUYf4UJ7oALX/9//6N6g==,type:str]
kind: ENC[AES256_GCM,data:OpVrXcMz,iv:kr1JnJO105cVY1dcMgvQ/ILaRz2NCvnoYBUT3FsyV8I=,tag:lKh59Or+SP/iHPmXLTF62w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W+e249uO36eH7B7ww17wO27gIdgLkIKIcLBIax0=,iv:R3HZrN82xvexFzz08pgd5n0je2NqPKv/sLCE1CDVgD8=,tag:eUlzjq192rugqnKdziBTYw==,type:str]
    namespace: ENC[AES256_GCM,data:kbp3dXuyHbO/G5JRpoC4,iv:7pKVbwCUbYk1nzn3minaW5f2J8db76ZqYV6Kfc8ZI48=,tag:+CYuXgl7TcMX6qLWOoGu/g==,type:str]
stringData:
    password: ENC[AES256_GCM,data:A4/pTrKQqPtS7tPDm0F++OtISnfhHONF,iv:YnsJ0gjC8hoqGDSxSB1m5jKPBCpl7JX/1cO3ZvwiDgE=,tag:WSgGpwccGnyrDnuUAsNNIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVTZ4VmJ6RnRRKzQzV0h0
            MXhCOWpBZ1ZvTjBSMENNdGIwc1ZNcHY4OGpjClJaeEMrY3Zqd1pVUVJiVEdnYTlK
            TFNjRjM1UzNHem94TUN4N2xWemxlS0UKLS0tIHZya3pxWmEzM1dSdlZ0Zmk5SHZM
            TFJBdGpic3kxV1VRWnlCMEd4RTJhYzQKNsqJgRbwrd/u21SOhkQiIBEh4E6dEom/
            jgvY4Fz8WBnABBZnIBexnhd+rw+fxc7Sh9hFSJB2zc1HvLWHd0GzBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:40:01Z"
    mac: ENC[AES256_GCM,data:arjcCQhBkdw3v6b/09gpTPpfH1TWL5/TYwSfMCF8fGLbZ07KrBT0R76O6dS9R7pk45+VipjX8rLuWvo6d9zMNxccYjulw4taNfYmcSfkqeXgHLN7Orqrc8m6gOrIO0owmhT6EDOPGWZqPYQmhgT8U8urFlg230ZOPrYGPqx/Q6g=,iv:1E3+7etKZAGLauxeqjh+x+DRIPrr7ZJnc24CQO+M7to=,tag:9OBWs0TkHfcBYcAUjzWFXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
