apiVersion: ENC[AES256_GCM,data:h9w=,iv:Q5D/2v1vatk1UGp6gm2zmaIZoG5wbNQ2aJgC5pRqpIk=,tag:7HTqgUDqqme6B4wZqabp6g==,type:str]
kind: ENC[AES256_GCM,data:elhtjQzR,iv:6C25eCQdJpUDsTzlE9qfgivOyj3X+0Fz2YkrO3PSqIo=,tag:pWZXWw//iOsELe+bAgUjPA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hdjdNtPjE8i66+ydE7sYkJcgQA==,iv:lt5EhldSriPIPkJyUm+g5lNXsincpVcQhKPCUcNnhZk=,tag:gB7HqbhGlkcCIdgICphhYA==,type:str]
    namespace: ENC[AES256_GCM,data:CEy0s3KW0dkF8SfRTVW7,iv:M39s8oX/4m63vD1aCi8XRXlRH1dNO/pO9gebEoQ+4Gw=,tag:Km5wgdUHqHrKJkJ6oERwZw==,type:str]
data:
    users: ENC[AES256_GCM,data:pXOAiIsYAC6S2QOYDjQfcTpTJjtaqtDzOo8C/6giGWH5TJLL6NSQgZORBOdUsLrrl7uPdgoK+vVMZICv,iv:0zqYQcjpJETq/LWIDuJxWPXamwJDX8dqe/guxcdJyzg=,tag:jXIt7m82RuvqANqj0BIevg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUXQ0LzRMNGEydDB5WWov
            QnpRaHEycG56MTdSOTJ4cHlTMnhGc3dVaWhRCnJTbWlaQlJMdTlNYmp4VDlENC8z
            RllmQ3hxdzhaeTd4UmhVSmhDSmwvY2sKLS0tIHVUdmtLYkQ0UWVjUkpxSkZzY2wx
            a2Y1Z1JwUmZHNmdzb1FiQXdVMkxvYU0KA+FxSSOY1mwbwuNpEZGaJFmzv7gEME0w
            rKksKu0wa1qeKx8lIXd2nU09sCC42ST/oZlK93s5b65/KCRJOOzWkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-05-14T14:25:59Z"
    mac: ENC[AES256_GCM,data:mNL5IfQGFhxG62zBSqJdPO6QxcVXhsCFC8HpYvV6WUlA4fK8CxRnCsshyt+pzsNO9W8DJr311aj9ekeYyxZ4YIwEciqjoXuFReXsYTyWWdqA3N6zHdtnkM7u+y4Hv15MkhFb25wPERddJAlbB4mfcQTxGSBG+YHK+8YKL7XCGUY=,iv:k+Cbl/ORhULCRq+zu/GVD/J+0TIOoIor3r++DyhaNOc=,tag:SbdBk6flEzpYyapxUQJeQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
