apiVersion: ENC[AES256_GCM,data:CRM=,iv:bVZY76vv6At7M1lF7nCZaB17hoajl5y/BpOUbovv3uc=,tag:kJx71JsZ8IshRCgxMrlMKA==,type:str]
kind: ENC[AES256_GCM,data:W/iAgVKs,iv:EnhH+21vs2RfaAHXE/NgSpC5MWQwoNcjjrKN/8dX2vc=,tag:W7V/FcCINzJXn7Rr09GDmw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xkwgUtEejb/eQAoEwuckfMJ6sw==,iv:uHezKY+Zcd05eYAJRgtbEwxW6CUudOHkA36S14BNHG4=,tag:tmA5/Nf0BdD0+4Lc2zh00A==,type:str]
    namespace: ENC[AES256_GCM,data:lvbxOJl59kDFMNBZGH0p,iv:SAQx44PLkec0EpfH87XDfNbQ/O+A9CHp1MwtzTA/IR4=,tag:B+pOVO9RM8/slTPwPqfEaQ==,type:str]
data:
    users: ENC[AES256_GCM,data:GKUmJ5rL1zbv+n59r31usJtWMZBdOZ3rg5Ddb5cJMdlZlqxgzM7ywJPVdN2yK3inN0LKOwutWtz93UHP,iv:ug1J0APoCTqEgSRpZq42wdGNsWkLDHJG0gtas32nrko=,tag:2BNALuxX5NcdcZL+9F18Vw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:YtxCGO22fkgCByH7jggVAqFWT6sJSopx,iv:S2R2DFpkPWIBsVFMibnxdQWZTSvI3Uo3hrklJBe8mW4=,tag:yOMswQkBcveLkB+LJMMVFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYnhMTWovSUhQbWhNblZN
            cjVEQWFRd3hwSmk1bnRzc0xIRFRuUDVUalVNCjJaTEtySnJ5QWV6NTZub2ExZ1dK
            Ny8veXZ5Yi9CYzRnc29XTDFDVTRkV28KLS0tIHlXVXQzODhubjFqRGcrQU9HRUE5
            ZzlQS09nZlpJYTdZQ3Z0elJOOVRsWHcKvrso6ncUnUmUuC7jPsBp6fybKOTooM/k
            Trm/S2FNf6CwaIoY4VGYZCZh41/Gha4ZedWf/TyVY4iEx0vuz44dnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:29:41Z"
    mac: ENC[AES256_GCM,data:8tL2cYzCPh2IGV1l/D34/IMKw/sWBRx38eoVMcwMHNVg+1VlgKySlTTxxWTIJnGj2HniVRo0j7JRE9v8srt1nlLeUsjUtoHqKGMaQOggBX+ysXlbk7saNbgnJUCVgHKew61CMMnqU8GVYsza1J2+g1n743hZ2F0IXVFPwn4ILfs=,iv:P1P/h/2QhkjbSkGYKD1m5a3TRQN/5lqWIc4uOk1H6yg=,tag:KgwkA3W5vkFu5lRtspU/HQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
