apiVersion: ENC[AES256_GCM,data:t9g=,iv:rU6x13ied0WSB7ElF++1dkeVC3IyiLwQDOVjY057M2M=,tag:jhUyGkt9fpFEdDw6KjUGyg==,type:str]
kind: ENC[AES256_GCM,data:MhnzlW81,iv:RQb7s08iKtztHD3a3MYRYzv+rn7ZyzVaD9gWTsmb3dk=,tag:G7TT9cLRStx78Wy3sKEpGw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Qo2UyRflnqYwewSutZUjLU27/g==,iv:CLcZC1fUhcn2rwor6pCA8NA1QCOsD/deOU3Wzqo39yk=,tag:oYyG47dY6yXirrjwbsG9PQ==,type:str]
    namespace: ENC[AES256_GCM,data:9FEZwgxfB8u+N9b+YX/r,iv:RtnO6OzwETpio7Ax06ZPfYakz2nJHpwv/Lk1/sq04fs=,tag:8NDPgx2kEMoSOtwV975HQA==,type:str]
data:
    users: ENC[AES256_GCM,data:/lV/e4JEmUfP/poVf65WiF1CPs1bz+WayCEppJyMzXaXLc/ruLwbvksEe/6TYrRG+4z/wtXy9VteU1Kp,iv:GcANReGZdTSdU0HvMEFezaE5YJv42poQ6xRXgvGDGMc=,tag:g4K3e+pEK517WxzHB7oazg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZHVLeHlkdWJITy8zYVVY
            TExPUjlPd0ZjMHJtS3BCaFFETUNqV01JSEhnCnlaWS9KVkRMTDVoZFpjNHNjV0hL
            SkFDY2E0MGNYMERaUG5za1F0NnYrZWMKLS0tIGY0VjNhV3lhUmM4RG9pY1M1K3ZC
            M0tKSWJwUkkvSnorcmExUzhmd2lwQnMK00TzYj5JdUa7lYdJc8H5bVfqkQ/F2Sgh
            VfER+Wit2HJw7x7FnC7e0B//rU4lAB0rcjKjVwiyBOHtnRKMWQC8zA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhpn7w8hv4x7lfwc7a8r4ycwvcqn6tz6tekhnlahc67l7ngt8y5qdqhxsr
    lastmodified: "2026-08-20T23:40:01Z"
    mac: ENC[AES256_GCM,data:qX91X3BjJWy+2THLmfBXCFAtPIMlQuu8ngn+h1zvVD0z+eEEctBtxoMBuDqkm7E+vqnPt9EdGjcUi6G5RnKYdY+ojn4ZMWcAnqfqqYzqHfoYvomQhsc66tvCsYis4yLdf2nBthzRbvQsWO6JVSf0WvydoxfxDAtjqn/lo3AGpFU=,iv:saG7mlqWyuRkw9Rimay3RMXd622TFuNbqfsH9KRIOes=,tag:QsUYQOMGCxyMbTYKBA0Gbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
